// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: api/behavior/v1/behavior.proto

package behaviorv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserBehaviorEventItem struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Event      string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Screen     string                 `protobuf:"bytes,2,opt,name=screen,proto3" json:"screen,omitempty"`
	Params     map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DurationMs int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	SessionId  string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ClientTs   int64                  `protobuf:"varint,6,opt,name=client_ts,json=clientTs,proto3" json:"client_ts,omitempty"`
	// 与 moe.UserBehaviorEventInput.params_json 对齐（gateway / 内部调用）
	ParamsJson    string `protobuf:"bytes,7,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBehaviorEventItem) Reset() {
	*x = UserBehaviorEventItem{}
	mi := &file_api_behavior_v1_behavior_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBehaviorEventItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBehaviorEventItem) ProtoMessage() {}

func (x *UserBehaviorEventItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_behavior_v1_behavior_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBehaviorEventItem.ProtoReflect.Descriptor instead.
func (*UserBehaviorEventItem) Descriptor() ([]byte, []int) {
	return file_api_behavior_v1_behavior_proto_rawDescGZIP(), []int{0}
}

func (x *UserBehaviorEventItem) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *UserBehaviorEventItem) GetScreen() string {
	if x != nil {
		return x.Screen
	}
	return ""
}

func (x *UserBehaviorEventItem) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *UserBehaviorEventItem) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *UserBehaviorEventItem) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UserBehaviorEventItem) GetClientTs() int64 {
	if x != nil {
		return x.ClientTs
	}
	return 0
}

func (x *UserBehaviorEventItem) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

type TrackUserBehaviorEventsRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	UserId        uint64                   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Events        []*UserBehaviorEventItem `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackUserBehaviorEventsRequest) Reset() {
	*x = TrackUserBehaviorEventsRequest{}
	mi := &file_api_behavior_v1_behavior_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackUserBehaviorEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackUserBehaviorEventsRequest) ProtoMessage() {}

func (x *TrackUserBehaviorEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_behavior_v1_behavior_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackUserBehaviorEventsRequest.ProtoReflect.Descriptor instead.
func (*TrackUserBehaviorEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_behavior_v1_behavior_proto_rawDescGZIP(), []int{1}
}

func (x *TrackUserBehaviorEventsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TrackUserBehaviorEventsRequest) GetEvents() []*UserBehaviorEventItem {
	if x != nil {
		return x.Events
	}
	return nil
}

type TrackUserBehaviorEventsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int32                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackUserBehaviorEventsReply) Reset() {
	*x = TrackUserBehaviorEventsReply{}
	mi := &file_api_behavior_v1_behavior_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackUserBehaviorEventsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackUserBehaviorEventsReply) ProtoMessage() {}

func (x *TrackUserBehaviorEventsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_behavior_v1_behavior_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackUserBehaviorEventsReply.ProtoReflect.Descriptor instead.
func (*TrackUserBehaviorEventsReply) Descriptor() ([]byte, []int) {
	return file_api_behavior_v1_behavior_proto_rawDescGZIP(), []int{2}
}

func (x *TrackUserBehaviorEventsReply) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

var File_api_behavior_v1_behavior_proto protoreflect.FileDescriptor

const file_api_behavior_v1_behavior_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/behavior/v1/behavior.proto\x12\vbehavior.v1\x1a\x1cgoogle/api/annotations.proto\"\xc6\x02\n" +
	"\x15UserBehaviorEventItem\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x16\n" +
	"\x06screen\x18\x02 \x01(\tR\x06screen\x12F\n" +
	"\x06params\x18\x03 \x03(\v2..behavior.v1.UserBehaviorEventItem.ParamsEntryR\x06params\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tclient_ts\x18\x06 \x01(\x03R\bclientTs\x12\x1f\n" +
	"\vparams_json\x18\a \x01(\tR\n" +
	"paramsJson\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"u\n" +
	"\x1eTrackUserBehaviorEventsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12:\n" +
	"\x06events\x18\x02 \x03(\v2\".behavior.v1.UserBehaviorEventItemR\x06events\":\n" +
	"\x1cTrackUserBehaviorEventsReply\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted2\xa5\x01\n" +
	"\vBehaviorApp\x12\x95\x01\n" +
	"\vTrackEvents\x12+.behavior.v1.TrackUserBehaviorEventsRequest\x1a).behavior.v1.TrackUserBehaviorEventsReply\".\x82\xd3\xe4\x93\x02(:\x01*\"#/api/user/{user_id}/behavior/eventsB$Z\"backend/api/behavior/v1;behaviorv1b\x06proto3"

var (
	file_api_behavior_v1_behavior_proto_rawDescOnce sync.Once
	file_api_behavior_v1_behavior_proto_rawDescData []byte
)

func file_api_behavior_v1_behavior_proto_rawDescGZIP() []byte {
	file_api_behavior_v1_behavior_proto_rawDescOnce.Do(func() {
		file_api_behavior_v1_behavior_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_behavior_v1_behavior_proto_rawDesc), len(file_api_behavior_v1_behavior_proto_rawDesc)))
	})
	return file_api_behavior_v1_behavior_proto_rawDescData
}

var file_api_behavior_v1_behavior_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_behavior_v1_behavior_proto_goTypes = []any{
	(*UserBehaviorEventItem)(nil),          // 0: behavior.v1.UserBehaviorEventItem
	(*TrackUserBehaviorEventsRequest)(nil), // 1: behavior.v1.TrackUserBehaviorEventsRequest
	(*TrackUserBehaviorEventsReply)(nil),   // 2: behavior.v1.TrackUserBehaviorEventsReply
	nil,                                    // 3: behavior.v1.UserBehaviorEventItem.ParamsEntry
}
var file_api_behavior_v1_behavior_proto_depIdxs = []int32{
	3, // 0: behavior.v1.UserBehaviorEventItem.params:type_name -> behavior.v1.UserBehaviorEventItem.ParamsEntry
	0, // 1: behavior.v1.TrackUserBehaviorEventsRequest.events:type_name -> behavior.v1.UserBehaviorEventItem
	1, // 2: behavior.v1.BehaviorApp.TrackEvents:input_type -> behavior.v1.TrackUserBehaviorEventsRequest
	2, // 3: behavior.v1.BehaviorApp.TrackEvents:output_type -> behavior.v1.TrackUserBehaviorEventsReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_behavior_v1_behavior_proto_init() }
func file_api_behavior_v1_behavior_proto_init() {
	if File_api_behavior_v1_behavior_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_behavior_v1_behavior_proto_rawDesc), len(file_api_behavior_v1_behavior_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_behavior_v1_behavior_proto_goTypes,
		DependencyIndexes: file_api_behavior_v1_behavior_proto_depIdxs,
		MessageInfos:      file_api_behavior_v1_behavior_proto_msgTypes,
	}.Build()
	File_api_behavior_v1_behavior_proto = out.File
	file_api_behavior_v1_behavior_proto_goTypes = nil
	file_api_behavior_v1_behavior_proto_depIdxs = nil
}
