package moehttp

import (
	"backend/api/internal/svc"
	hadmin "backend/api/internal/handler/admin"

	khttp "github.com/go-kratos/kratos/v2/transport/http"
)

// PilotNativeAdminLogicCompatRoutes 波次3：logic 薄转（待二期 internal/service）。
const PilotNativeAdminLogicCompatRoutes = 83

// RegisterAdminLogicCompat 注册 HTTP。
func RegisterAdminLogicCompat(srv *khttp.Server, svc *svc.ServiceContext) {
	if srv == nil || svc == nil {
		return
	}
	r := srv.Route("/")
	r.GET("/api/admin/accounts", wrapNativeHTTP(hadmin.AdminListAccountsHandler(svc)))
	r.POST("/api/admin/accounts", wrapNativeHTTP(hadmin.AdminCreateAccountHandler(svc)))
	r.PUT("/api/admin/accounts/:account_id", wrapNativeHTTP(hadmin.AdminUpdateAccountHandler(svc)))
	r.DELETE("/api/admin/accounts/:account_id", wrapNativeHTTP(hadmin.AdminDeleteAccountHandler(svc)))
	r.POST("/api/admin/achievements/bootstrap", wrapNativeHTTP(hadmin.AdminBootstrapAchievementsHandler(svc)))
	r.GET("/api/admin/ai/agents", wrapNativeHTTP(hadmin.AdminListAiAgentsHandler(svc)))
	r.DELETE("/api/admin/ai/agents", wrapNativeHTTP(hadmin.AdminDeleteAiAgentHandler(svc)))
	r.PUT("/api/admin/ai/agents", wrapNativeHTTP(hadmin.AdminUpdateAiAgentHandler(svc)))
	r.GET("/api/admin/announcements", wrapNativeHTTP(hadmin.AdminListAnnouncementsHandler(svc)))
	r.POST("/api/admin/announcements", wrapNativeHTTP(hadmin.AdminCreateAnnouncementHandler(svc)))
	r.GET("/api/admin/announcements/:announcement_id", wrapNativeHTTP(hadmin.AdminGetAnnouncementHandler(svc)))
	r.PUT("/api/admin/announcements/:announcement_id", wrapNativeHTTP(hadmin.AdminUpdateAnnouncementHandler(svc)))
	r.DELETE("/api/admin/announcements/:announcement_id", wrapNativeHTTP(hadmin.AdminDeleteAnnouncementHandler(svc)))
	r.POST("/api/admin/announcements/:announcement_id/publish", wrapNativeHTTP(hadmin.AdminPublishAnnouncementHandler(svc)))
	r.GET("/api/admin/audit-logs", wrapNativeHTTP(hadmin.AdminListAuditLogsHandler(svc)))
	r.GET("/api/admin/comments", wrapNativeHTTP(hadmin.AdminListCommentsHandler(svc)))
	r.DELETE("/api/admin/comments/:comment_id", wrapNativeHTTP(hadmin.AdminDeleteCommentHandler(svc)))
	r.GET("/api/admin/community/groups", wrapNativeHTTP(hadmin.AdminListGroupsHandler(svc)))
	r.DELETE("/api/admin/community/groups/:group_id", wrapNativeHTTP(hadmin.AdminDeleteGroupHandler(svc)))
	r.GET("/api/admin/gifts", wrapNativeHTTP(hadmin.AdminListGiftsHandler(svc)))
	r.POST("/api/admin/gifts", wrapNativeHTTP(hadmin.AdminCreateGiftHandler(svc)))
	r.GET("/api/admin/gifts/:gift_id", wrapNativeHTTP(hadmin.AdminGetGiftHandler(svc)))
	r.PUT("/api/admin/gifts/:gift_id", wrapNativeHTTP(hadmin.AdminUpdateGiftHandler(svc)))
	r.DELETE("/api/admin/gifts/:gift_id", wrapNativeHTTP(hadmin.AdminDeleteGiftHandler(svc)))
	r.POST("/api/admin/gifts/bootstrap", wrapNativeHTTP(hadmin.AdminBootstrapGiftsHandler(svc)))
	r.POST("/api/admin/gifts/dedupe", wrapNativeHTTP(hadmin.AdminDedupeGiftsHandler(svc)))
	r.GET("/api/admin/growth/achievements", wrapNativeHTTP(hadmin.AdminListAchievementsHandler(svc)))
	r.PUT("/api/admin/growth/achievements/:achievement_id", wrapNativeHTTP(hadmin.AdminUpdateAchievementHandler(svc)))
	r.GET("/api/admin/growth/levels", wrapNativeHTTP(hadmin.AdminListLevelConfigsHandler(svc)))
	r.PUT("/api/admin/growth/levels/:level_id", wrapNativeHTTP(hadmin.AdminUpdateLevelConfigHandler(svc)))
	r.POST("/api/admin/growth/levels/bootstrap", wrapNativeHTTP(hadmin.AdminBootstrapLevelsHandler(svc)))
	r.GET("/api/admin/me", wrapNativeHTTP(hadmin.AdminMeHandler(svc)))
	r.GET("/api/admin/media/images", wrapNativeHTTP(hadmin.AdminListMediaImagesHandler(svc)))
	r.DELETE("/api/admin/media/images/:filename", wrapNativeHTTP(hadmin.AdminDeleteMediaImageHandler(svc)))
	r.GET("/api/admin/memories", wrapNativeHTTP(hadmin.AdminListMemoriesHandler(svc)))
	r.DELETE("/api/admin/memories/:memory_id", wrapNativeHTTP(hadmin.AdminDeleteMemoryHandler(svc)))
	r.GET("/api/admin/memories/stats", wrapNativeHTTP(hadmin.AdminGetMemoryStatsHandler(svc)))
	r.GET("/api/admin/menus", wrapNativeHTTP(hadmin.AdminListMenusHandler(svc)))
	r.PUT("/api/admin/menus", wrapNativeHTTP(hadmin.AdminUpsertMenuHandler(svc)))
	r.DELETE("/api/admin/menus/:menu_key", wrapNativeHTTP(hadmin.AdminDeleteMenuHandler(svc)))
	r.POST("/api/admin/menus/bootstrap", wrapNativeHTTP(hadmin.AdminBootstrapMenusHandler(svc)))
	r.DELETE("/api/admin/moe/brain/episodes/:id", wrapNativeHTTP(hadmin.AdminDeleteMoeBrainEpisodeHandler(svc)))
	r.POST("/api/admin/moe/brain/episodes/:id/refine", wrapNativeHTTP(hadmin.AdminRefineMoeBrainEpisodeHandler(svc)))
	r.GET("/api/admin/moe/brain/pipeline/stream", wrapNativeHTTP(hadmin.AdminStreamMoeBrainPipelineHandler(svc)))
	r.GET("/api/admin/moe/inference/status", wrapNativeHTTP(hadmin.AdminGetMoeInferenceStatusHandler(svc)))
	r.GET("/api/admin/moe/runtimes/:agent_key/brain", wrapNativeHTTP(hadmin.AdminGetMoeBrainHandler(svc)))
	r.POST("/api/admin/moe/runtimes/:agent_key/brain/curate", wrapNativeHTTP(hadmin.AdminCurateMoeBrainHandler(svc)))
	r.PUT("/api/admin/moe/runtimes/:agent_key/brain/policy", wrapNativeHTTP(hadmin.AdminUpdateMoeBrainPolicyHandler(svc)))
	r.GET("/api/admin/moe/runtimes/:agent_key/flow", wrapNativeHTTP(hadmin.AdminGetMoeBotFlowHandler(svc)))
	r.PUT("/api/admin/moe/runtimes/:agent_key/flow", wrapNativeHTTP(hadmin.AdminUpsertMoeBotFlowHandler(svc)))
	r.DELETE("/api/admin/moe/runtimes/:agent_key/flow", wrapNativeHTTP(hadmin.AdminDeleteMoeBotFlowHandler(svc)))
	r.POST("/api/admin/moe/runtimes/:agent_key/run-once", wrapNativeHTTP(hadmin.AdminRunMoeAgentOnceHandler(svc)))
	r.GET("/api/admin/moe/tools/calls", wrapNativeHTTP(hadmin.AdminListMoeToolCallsHandler(svc)))
	r.GET("/api/admin/moe/tools/schema", wrapNativeHTTP(hadmin.AdminGetMoeToolsSchemaHandler(svc)))
	r.GET("/api/admin/moe/tools/stats", wrapNativeHTTP(hadmin.AdminGetMoeToolStatsHandler(svc)))
	r.POST("/api/admin/notifications/broadcast", wrapNativeHTTP(hadmin.AdminBroadcastNotificationHandler(svc)))
	r.POST("/api/admin/notifications/send", wrapNativeHTTP(hadmin.AdminSendNotificationHandler(svc)))
	r.GET("/api/admin/orders/gift-purchase", wrapNativeHTTP(hadmin.AdminListGiftPurchaseOrdersHandler(svc)))
	r.GET("/api/admin/orders/vip", wrapNativeHTTP(hadmin.AdminListVipOrdersHandler(svc)))
	r.GET("/api/admin/post-reports", wrapNativeHTTP(hadmin.AdminListPostReportsHandler(svc)))
	r.GET("/api/admin/posts", wrapNativeHTTP(hadmin.AdminListPostsHandler(svc)))
	r.DELETE("/api/admin/posts/:post_id", wrapNativeHTTP(hadmin.AdminDeletePostHandler(svc)))
	r.GET("/api/admin/runtime-config", wrapNativeHTTP(hadmin.AdminGetRuntimeConfigHandler(svc)))
	r.PUT("/api/admin/runtime-config", wrapNativeHTTP(hadmin.AdminUpdateRuntimeConfigHandler(svc)))
	r.GET("/api/admin/runtime/overview", wrapNativeHTTP(hadmin.AdminRuntimeOverviewHandler(svc)))
	r.GET("/api/admin/social/follows", wrapNativeHTTP(hadmin.AdminListFollowsHandler(svc)))
	r.DELETE("/api/admin/social/follows/:follow_id", wrapNativeHTTP(hadmin.AdminDeleteFollowHandler(svc)))
	r.GET("/api/admin/social/friend-requests", wrapNativeHTTP(hadmin.AdminListFriendRequestsHandler(svc)))
	r.GET("/api/admin/tag-dictionary", wrapNativeHTTP(hadmin.AdminListTagDictionaryHandler(svc)))
	r.POST("/api/admin/tag-dictionary", wrapNativeHTTP(hadmin.AdminCreateTagDictionaryHandler(svc)))
	r.PUT("/api/admin/tag-dictionary/:entry_id", wrapNativeHTTP(hadmin.AdminUpdateTagDictionaryHandler(svc)))
	r.DELETE("/api/admin/tag-dictionary/:entry_id", wrapNativeHTTP(hadmin.AdminDeleteTagDictionaryHandler(svc)))
	r.PUT("/api/admin/topic-tags/:tag_id", wrapNativeHTTP(hadmin.AdminUpdateTopicTagHandler(svc)))
	r.DELETE("/api/admin/topic-tags/:tag_id", wrapNativeHTTP(hadmin.AdminDeleteTopicTagHandler(svc)))
	r.POST("/api/admin/topic-tags/bootstrap", wrapNativeHTTP(hadmin.AdminBootstrapTopicTagsHandler(svc)))
	r.GET("/api/admin/users", wrapNativeHTTP(hadmin.AdminListUsersHandler(svc)))
	r.GET("/api/admin/users/:user_id", wrapNativeHTTP(hadmin.AdminGetUserHandler(svc)))
	r.PUT("/api/admin/users/:user_id", wrapNativeHTTP(hadmin.AdminUpdateUserHandler(svc)))
	r.GET("/api/admin/users/:user_id/profile", wrapNativeHTTP(hadmin.AdminGetUserProfileHandler(svc)))
	r.GET("/api/admin/vip/plans/:plan_id", wrapNativeHTTP(hadmin.AdminGetVipPlanHandler(svc)))
	r.PUT("/api/admin/vip/plans/:plan_id", wrapNativeHTTP(hadmin.AdminUpdateVipPlanHandler(svc)))
	r.DELETE("/api/admin/vip/plans/:plan_id", wrapNativeHTTP(hadmin.AdminDeleteVipPlanHandler(svc)))
	r.POST("/api/admin/vip/plans/bootstrap", wrapNativeHTTP(hadmin.AdminBootstrapVipPlansHandler(svc)))
}
