// Code generated by scripts/gen/http-routes; DO NOT EDIT.

package moehttp

import (
	"backend/api/internal/svc"
	hdoc "backend/api/internal/handler/doc"

	khttp "github.com/go-kratos/kratos/v2/transport/http"
)

const bridgeRouteCount = 2

func RegisterBridgeHTTPHandlers(srv *khttp.Server, svc *svc.ServiceContext) {
	if srv == nil || svc == nil {
		return
	}
	r := srv.Route("/")
	r.GET("/swagger", wrapNetHTTPHandler(hdoc.SwaggerUiHandler(svc)))
	r.GET("/swagger/doc.json", wrapNetHTTPHandler(hdoc.SwaggerDocHandler(svc)))
}
