// Code generated by scripts/gen/http-routes; DO NOT EDIT.

package moehttp

import (
	"backend/api/internal/svc"

	khttp "github.com/go-kratos/kratos/v2/transport/http"
)

const nativeDomainRouteCount = 0

func RegisterNativeDomainHTTPHandlers(srv *khttp.Server, svc *svc.ServiceContext) {
	if srv == nil || svc == nil {
		return
	}
	return
}
