services:
  rpc:
    build:
      context: .
      dockerfile: Dockerfile.binary.rpc
    container_name: moe-social-rpc
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./rpc/moe-social-rpc:/app/rpc/moe-social-rpc
      - ./rpc/etc:/app/rpc/etc
      - ./config:/app/config
    networks:
      - moe-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.binary.api
    container_name: moe-social-api
    restart: always
    ports:
      - "8888:8888"
    depends_on:
      - rpc
    volumes:
      - ./api/moe-social-api:/app/api/moe-social-api
      - ./api/etc:/app/etc
      - ./config:/app/config
      - ./data/images:/app/data/images
    networks:
      - moe-network

networks:
  moe-network:
    driver: bridge