services:
  moe-social:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moe-social
    ports:
      - "8888:8888"
    volumes:
      - /root/gowork/moe_images:/app/data/images
    restart: unless-stopped
