// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/moe/v1/moe.proto

package moev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MoeAdmin_ListRuntimes_FullMethodName       = "/moe.v1.MoeAdmin/ListRuntimes"
	MoeAdmin_UpsertRuntime_FullMethodName      = "/moe.v1.MoeAdmin/UpsertRuntime"
	MoeAdmin_GetBrainPipeline_FullMethodName   = "/moe.v1.MoeAdmin/GetBrainPipeline"
	MoeAdmin_RunAgentOnce_FullMethodName       = "/moe.v1.MoeAdmin/RunAgentOnce"
	MoeAdmin_GetBrainSnapshot_FullMethodName   = "/moe.v1.MoeAdmin/GetBrainSnapshot"
	MoeAdmin_UpdateBrainPolicy_FullMethodName  = "/moe.v1.MoeAdmin/UpdateBrainPolicy"
	MoeAdmin_DeleteBrainEpisode_FullMethodName = "/moe.v1.MoeAdmin/DeleteBrainEpisode"
	MoeAdmin_RefineBrainEpisode_FullMethodName = "/moe.v1.MoeAdmin/RefineBrainEpisode"
	MoeAdmin_CurateBrain_FullMethodName        = "/moe.v1.MoeAdmin/CurateBrain"
	MoeAdmin_QueryToolStats_FullMethodName     = "/moe.v1.MoeAdmin/QueryToolStats"
	MoeAdmin_ListToolCalls_FullMethodName      = "/moe.v1.MoeAdmin/ListToolCalls"
)

// MoeAdminClient is the client API for MoeAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MoeAdmin — PK-1 域 SSOT。HTTP 灰度读路径（PK-2）：
//
//	GET /api/admin/moe/runtimes
//	GET /api/admin/moe/brain/pipeline?agent_key=
//
// 试点 :19032；灰度 moe.kratos_admin_http_enabled
type MoeAdminClient interface {
	ListRuntimes(ctx context.Context, in *ListRuntimesRequest, opts ...grpc.CallOption) (*ListRuntimesReply, error)
	UpsertRuntime(ctx context.Context, in *UpsertRuntimeRequest, opts ...grpc.CallOption) (*UpsertRuntimeReply, error)
	GetBrainPipeline(ctx context.Context, in *GetBrainPipelineRequest, opts ...grpc.CallOption) (*GetBrainPipelineReply, error)
	RunAgentOnce(ctx context.Context, in *RunAgentOnceRequest, opts ...grpc.CallOption) (*RunAgentOnceReply, error)
	GetBrainSnapshot(ctx context.Context, in *GetBrainSnapshotRequest, opts ...grpc.CallOption) (*GetBrainSnapshotReply, error)
	UpdateBrainPolicy(ctx context.Context, in *UpdateBrainPolicyRequest, opts ...grpc.CallOption) (*GetBrainSnapshotReply, error)
	DeleteBrainEpisode(ctx context.Context, in *DeleteBrainEpisodeRequest, opts ...grpc.CallOption) (*DeleteBrainEpisodeReply, error)
	RefineBrainEpisode(ctx context.Context, in *RefineBrainEpisodeRequest, opts ...grpc.CallOption) (*RefineBrainEpisodeReply, error)
	CurateBrain(ctx context.Context, in *CurateBrainRequest, opts ...grpc.CallOption) (*CurateBrainReply, error)
	QueryToolStats(ctx context.Context, in *QueryToolStatsRequest, opts ...grpc.CallOption) (*QueryToolStatsReply, error)
	ListToolCalls(ctx context.Context, in *ListToolCallsRequest, opts ...grpc.CallOption) (*ListToolCallsReply, error)
}

type moeAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewMoeAdminClient(cc grpc.ClientConnInterface) MoeAdminClient {
	return &moeAdminClient{cc}
}

func (c *moeAdminClient) ListRuntimes(ctx context.Context, in *ListRuntimesRequest, opts ...grpc.CallOption) (*ListRuntimesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRuntimesReply)
	err := c.cc.Invoke(ctx, MoeAdmin_ListRuntimes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moeAdminClient) UpsertRuntime(ctx context.Context, in *UpsertRuntimeRequest, opts ...grpc.CallOption) (*UpsertRuntimeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertRuntimeReply)
	err := c.cc.Invoke(ctx, MoeAdmin_UpsertRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moeAdminClient) GetBrainPipeline(ctx context.Context, in *GetBrainPipelineRequest, opts ...grpc.CallOption) (*GetBrainPipelineReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBrainPipelineReply)
	err := c.cc.Invoke(ctx, MoeAdmin_GetBrainPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moeAdminClient) RunAgentOnce(ctx context.Context, in *RunAgentOnceRequest, opts ...grpc.CallOption) (*RunAgentOnceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunAgentOnceReply)
	err := c.cc.Invoke(ctx, MoeAdmin_RunAgentOnce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moeAdminClient) GetBrainSnapshot(ctx context.Context, in *GetBrainSnapshotRequest, opts ...grpc.CallOption) (*GetBrainSnapshotReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBrainSnapshotReply)
	err := c.cc.Invoke(ctx, MoeAdmin_GetBrainSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moeAdminClient) UpdateBrainPolicy(ctx context.Context, in *UpdateBrainPolicyRequest, opts ...grpc.CallOption) (*GetBrainSnapshotReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBrainSnapshotReply)
	err := c.cc.Invoke(ctx, MoeAdmin_UpdateBrainPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moeAdminClient) DeleteBrainEpisode(ctx context.Context, in *DeleteBrainEpisodeRequest, opts ...grpc.CallOption) (*DeleteBrainEpisodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBrainEpisodeReply)
	err := c.cc.Invoke(ctx, MoeAdmin_DeleteBrainEpisode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moeAdminClient) RefineBrainEpisode(ctx context.Context, in *RefineBrainEpisodeRequest, opts ...grpc.CallOption) (*RefineBrainEpisodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefineBrainEpisodeReply)
	err := c.cc.Invoke(ctx, MoeAdmin_RefineBrainEpisode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moeAdminClient) CurateBrain(ctx context.Context, in *CurateBrainRequest, opts ...grpc.CallOption) (*CurateBrainReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CurateBrainReply)
	err := c.cc.Invoke(ctx, MoeAdmin_CurateBrain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moeAdminClient) QueryToolStats(ctx context.Context, in *QueryToolStatsRequest, opts ...grpc.CallOption) (*QueryToolStatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryToolStatsReply)
	err := c.cc.Invoke(ctx, MoeAdmin_QueryToolStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moeAdminClient) ListToolCalls(ctx context.Context, in *ListToolCallsRequest, opts ...grpc.CallOption) (*ListToolCallsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListToolCallsReply)
	err := c.cc.Invoke(ctx, MoeAdmin_ListToolCalls_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoeAdminServer is the server API for MoeAdmin service.
// All implementations must embed UnimplementedMoeAdminServer
// for forward compatibility.
//
// MoeAdmin — PK-1 域 SSOT。HTTP 灰度读路径（PK-2）：
//
//	GET /api/admin/moe/runtimes
//	GET /api/admin/moe/brain/pipeline?agent_key=
//
// 试点 :19032；灰度 moe.kratos_admin_http_enabled
type MoeAdminServer interface {
	ListRuntimes(context.Context, *ListRuntimesRequest) (*ListRuntimesReply, error)
	UpsertRuntime(context.Context, *UpsertRuntimeRequest) (*UpsertRuntimeReply, error)
	GetBrainPipeline(context.Context, *GetBrainPipelineRequest) (*GetBrainPipelineReply, error)
	RunAgentOnce(context.Context, *RunAgentOnceRequest) (*RunAgentOnceReply, error)
	GetBrainSnapshot(context.Context, *GetBrainSnapshotRequest) (*GetBrainSnapshotReply, error)
	UpdateBrainPolicy(context.Context, *UpdateBrainPolicyRequest) (*GetBrainSnapshotReply, error)
	DeleteBrainEpisode(context.Context, *DeleteBrainEpisodeRequest) (*DeleteBrainEpisodeReply, error)
	RefineBrainEpisode(context.Context, *RefineBrainEpisodeRequest) (*RefineBrainEpisodeReply, error)
	CurateBrain(context.Context, *CurateBrainRequest) (*CurateBrainReply, error)
	QueryToolStats(context.Context, *QueryToolStatsRequest) (*QueryToolStatsReply, error)
	ListToolCalls(context.Context, *ListToolCallsRequest) (*ListToolCallsReply, error)
	mustEmbedUnimplementedMoeAdminServer()
}

// UnimplementedMoeAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMoeAdminServer struct{}

func (UnimplementedMoeAdminServer) ListRuntimes(context.Context, *ListRuntimesRequest) (*ListRuntimesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuntimes not implemented")
}
func (UnimplementedMoeAdminServer) UpsertRuntime(context.Context, *UpsertRuntimeRequest) (*UpsertRuntimeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertRuntime not implemented")
}
func (UnimplementedMoeAdminServer) GetBrainPipeline(context.Context, *GetBrainPipelineRequest) (*GetBrainPipelineReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBrainPipeline not implemented")
}
func (UnimplementedMoeAdminServer) RunAgentOnce(context.Context, *RunAgentOnceRequest) (*RunAgentOnceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RunAgentOnce not implemented")
}
func (UnimplementedMoeAdminServer) GetBrainSnapshot(context.Context, *GetBrainSnapshotRequest) (*GetBrainSnapshotReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBrainSnapshot not implemented")
}
func (UnimplementedMoeAdminServer) UpdateBrainPolicy(context.Context, *UpdateBrainPolicyRequest) (*GetBrainSnapshotReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBrainPolicy not implemented")
}
func (UnimplementedMoeAdminServer) DeleteBrainEpisode(context.Context, *DeleteBrainEpisodeRequest) (*DeleteBrainEpisodeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBrainEpisode not implemented")
}
func (UnimplementedMoeAdminServer) RefineBrainEpisode(context.Context, *RefineBrainEpisodeRequest) (*RefineBrainEpisodeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RefineBrainEpisode not implemented")
}
func (UnimplementedMoeAdminServer) CurateBrain(context.Context, *CurateBrainRequest) (*CurateBrainReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CurateBrain not implemented")
}
func (UnimplementedMoeAdminServer) QueryToolStats(context.Context, *QueryToolStatsRequest) (*QueryToolStatsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryToolStats not implemented")
}
func (UnimplementedMoeAdminServer) ListToolCalls(context.Context, *ListToolCallsRequest) (*ListToolCallsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListToolCalls not implemented")
}
func (UnimplementedMoeAdminServer) mustEmbedUnimplementedMoeAdminServer() {}
func (UnimplementedMoeAdminServer) testEmbeddedByValue()                  {}

// UnsafeMoeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MoeAdminServer will
// result in compilation errors.
type UnsafeMoeAdminServer interface {
	mustEmbedUnimplementedMoeAdminServer()
}

func RegisterMoeAdminServer(s grpc.ServiceRegistrar, srv MoeAdminServer) {
	// If the following call panics, it indicates UnimplementedMoeAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MoeAdmin_ServiceDesc, srv)
}

func _MoeAdmin_ListRuntimes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRuntimesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoeAdminServer).ListRuntimes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoeAdmin_ListRuntimes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoeAdminServer).ListRuntimes(ctx, req.(*ListRuntimesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoeAdmin_UpsertRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoeAdminServer).UpsertRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoeAdmin_UpsertRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoeAdminServer).UpsertRuntime(ctx, req.(*UpsertRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoeAdmin_GetBrainPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBrainPipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoeAdminServer).GetBrainPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoeAdmin_GetBrainPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoeAdminServer).GetBrainPipeline(ctx, req.(*GetBrainPipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoeAdmin_RunAgentOnce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunAgentOnceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoeAdminServer).RunAgentOnce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoeAdmin_RunAgentOnce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoeAdminServer).RunAgentOnce(ctx, req.(*RunAgentOnceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoeAdmin_GetBrainSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBrainSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoeAdminServer).GetBrainSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoeAdmin_GetBrainSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoeAdminServer).GetBrainSnapshot(ctx, req.(*GetBrainSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoeAdmin_UpdateBrainPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBrainPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoeAdminServer).UpdateBrainPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoeAdmin_UpdateBrainPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoeAdminServer).UpdateBrainPolicy(ctx, req.(*UpdateBrainPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoeAdmin_DeleteBrainEpisode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBrainEpisodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoeAdminServer).DeleteBrainEpisode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoeAdmin_DeleteBrainEpisode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoeAdminServer).DeleteBrainEpisode(ctx, req.(*DeleteBrainEpisodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoeAdmin_RefineBrainEpisode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefineBrainEpisodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoeAdminServer).RefineBrainEpisode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoeAdmin_RefineBrainEpisode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoeAdminServer).RefineBrainEpisode(ctx, req.(*RefineBrainEpisodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoeAdmin_CurateBrain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurateBrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoeAdminServer).CurateBrain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoeAdmin_CurateBrain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoeAdminServer).CurateBrain(ctx, req.(*CurateBrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoeAdmin_QueryToolStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryToolStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoeAdminServer).QueryToolStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoeAdmin_QueryToolStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoeAdminServer).QueryToolStats(ctx, req.(*QueryToolStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoeAdmin_ListToolCalls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolCallsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoeAdminServer).ListToolCalls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoeAdmin_ListToolCalls_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoeAdminServer).ListToolCalls(ctx, req.(*ListToolCallsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MoeAdmin_ServiceDesc is the grpc.ServiceDesc for MoeAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MoeAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moe.v1.MoeAdmin",
	HandlerType: (*MoeAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRuntimes",
			Handler:    _MoeAdmin_ListRuntimes_Handler,
		},
		{
			MethodName: "UpsertRuntime",
			Handler:    _MoeAdmin_UpsertRuntime_Handler,
		},
		{
			MethodName: "GetBrainPipeline",
			Handler:    _MoeAdmin_GetBrainPipeline_Handler,
		},
		{
			MethodName: "RunAgentOnce",
			Handler:    _MoeAdmin_RunAgentOnce_Handler,
		},
		{
			MethodName: "GetBrainSnapshot",
			Handler:    _MoeAdmin_GetBrainSnapshot_Handler,
		},
		{
			MethodName: "UpdateBrainPolicy",
			Handler:    _MoeAdmin_UpdateBrainPolicy_Handler,
		},
		{
			MethodName: "DeleteBrainEpisode",
			Handler:    _MoeAdmin_DeleteBrainEpisode_Handler,
		},
		{
			MethodName: "RefineBrainEpisode",
			Handler:    _MoeAdmin_RefineBrainEpisode_Handler,
		},
		{
			MethodName: "CurateBrain",
			Handler:    _MoeAdmin_CurateBrain_Handler,
		},
		{
			MethodName: "QueryToolStats",
			Handler:    _MoeAdmin_QueryToolStats_Handler,
		},
		{
			MethodName: "ListToolCalls",
			Handler:    _MoeAdmin_ListToolCalls_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/moe/v1/moe.proto",
}
