// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/admin/v1/admin.proto

package adminv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminApp_Ping_FullMethodName = "/admin.v1.AdminApp/Ping"
)

// AdminAppClient is the client API for AdminApp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminAppClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
}

type adminAppClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminAppClient(cc grpc.ClientConnInterface) AdminAppClient {
	return &adminAppClient{cc}
}

func (c *adminAppClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingReply)
	err := c.cc.Invoke(ctx, AdminApp_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminAppServer is the server API for AdminApp service.
// All implementations must embed UnimplementedAdminAppServer
// for forward compatibility.
type AdminAppServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	mustEmbedUnimplementedAdminAppServer()
}

// UnimplementedAdminAppServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminAppServer struct{}

func (UnimplementedAdminAppServer) Ping(context.Context, *PingRequest) (*PingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAdminAppServer) mustEmbedUnimplementedAdminAppServer() {}
func (UnimplementedAdminAppServer) testEmbeddedByValue()                  {}

// UnsafeAdminAppServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminAppServer will
// result in compilation errors.
type UnsafeAdminAppServer interface {
	mustEmbedUnimplementedAdminAppServer()
}

func RegisterAdminAppServer(s grpc.ServiceRegistrar, srv AdminAppServer) {
	// If the following call panics, it indicates UnimplementedAdminAppServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminApp_ServiceDesc, srv)
}

func _AdminApp_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAppServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminApp_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAppServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminApp_ServiceDesc is the grpc.ServiceDesc for AdminApp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminApp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.v1.AdminApp",
	HandlerType: (*AdminAppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _AdminApp_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/admin/v1/admin.proto",
}
