// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.1
// source: api/admin/v1/admin_messages.proto

package adminv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAdminInsightsAdminAnalyticsOverview = "/admin.v1.AdminInsights/AdminAnalyticsOverview"
const OperationAdminInsightsAdminExportAiChatMessages = "/admin.v1.AdminInsights/AdminExportAiChatMessages"
const OperationAdminInsightsAdminListAiChatMessages = "/admin.v1.AdminInsights/AdminListAiChatMessages"
const OperationAdminInsightsAdminListAiChatSessions = "/admin.v1.AdminInsights/AdminListAiChatSessions"
const OperationAdminInsightsAdminListTopicTags = "/admin.v1.AdminInsights/AdminListTopicTags"

type AdminInsightsHTTPServer interface {
	AdminAnalyticsOverview(context.Context, *AdminGetMemoryStatsReq) (*AdminAnalyticsOverviewResp, error)
	AdminExportAiChatMessages(context.Context, *AdminExportAiChatMessagesReq) (*AdminExportAiChatMessagesResp, error)
	AdminListAiChatMessages(context.Context, *AdminListAiChatMessagesReq) (*AdminListAiChatMessagesResp, error)
	AdminListAiChatSessions(context.Context, *AdminListAiChatSessionsReq) (*AdminListAiChatSessionsResp, error)
	AdminListTopicTags(context.Context, *AdminListTopicTagsReq) (*AdminListTopicTagsResp, error)
}

func RegisterAdminInsightsHTTPServer(s *http.Server, srv AdminInsightsHTTPServer) {
	r := s.Route("/")
	r.GET("/api/admin/ai/chat/sessions", _AdminInsights_AdminListAiChatSessions0_HTTP_Handler(srv))
	r.GET("/api/admin/ai/chat/messages", _AdminInsights_AdminListAiChatMessages0_HTTP_Handler(srv))
	r.GET("/api/admin/ai/chat/messages/export", _AdminInsights_AdminExportAiChatMessages0_HTTP_Handler(srv))
	r.GET("/api/admin/analytics/overview", _AdminInsights_AdminAnalyticsOverview0_HTTP_Handler(srv))
	r.GET("/api/admin/topic-tags", _AdminInsights_AdminListTopicTags0_HTTP_Handler(srv))
}

func _AdminInsights_AdminListAiChatSessions0_HTTP_Handler(srv AdminInsightsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AdminListAiChatSessionsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminInsightsAdminListAiChatSessions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AdminListAiChatSessions(ctx, req.(*AdminListAiChatSessionsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminListAiChatSessionsResp)
		return ctx.Result(200, reply)
	}
}

func _AdminInsights_AdminListAiChatMessages0_HTTP_Handler(srv AdminInsightsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AdminListAiChatMessagesReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminInsightsAdminListAiChatMessages)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AdminListAiChatMessages(ctx, req.(*AdminListAiChatMessagesReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminListAiChatMessagesResp)
		return ctx.Result(200, reply)
	}
}

func _AdminInsights_AdminExportAiChatMessages0_HTTP_Handler(srv AdminInsightsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AdminExportAiChatMessagesReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminInsightsAdminExportAiChatMessages)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AdminExportAiChatMessages(ctx, req.(*AdminExportAiChatMessagesReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminExportAiChatMessagesResp)
		return ctx.Result(200, reply)
	}
}

func _AdminInsights_AdminAnalyticsOverview0_HTTP_Handler(srv AdminInsightsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AdminGetMemoryStatsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminInsightsAdminAnalyticsOverview)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AdminAnalyticsOverview(ctx, req.(*AdminGetMemoryStatsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminAnalyticsOverviewResp)
		return ctx.Result(200, reply)
	}
}

func _AdminInsights_AdminListTopicTags0_HTTP_Handler(srv AdminInsightsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AdminListTopicTagsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminInsightsAdminListTopicTags)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AdminListTopicTags(ctx, req.(*AdminListTopicTagsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminListTopicTagsResp)
		return ctx.Result(200, reply)
	}
}

type AdminInsightsHTTPClient interface {
	AdminAnalyticsOverview(ctx context.Context, req *AdminGetMemoryStatsReq, opts ...http.CallOption) (rsp *AdminAnalyticsOverviewResp, err error)
	AdminExportAiChatMessages(ctx context.Context, req *AdminExportAiChatMessagesReq, opts ...http.CallOption) (rsp *AdminExportAiChatMessagesResp, err error)
	AdminListAiChatMessages(ctx context.Context, req *AdminListAiChatMessagesReq, opts ...http.CallOption) (rsp *AdminListAiChatMessagesResp, err error)
	AdminListAiChatSessions(ctx context.Context, req *AdminListAiChatSessionsReq, opts ...http.CallOption) (rsp *AdminListAiChatSessionsResp, err error)
	AdminListTopicTags(ctx context.Context, req *AdminListTopicTagsReq, opts ...http.CallOption) (rsp *AdminListTopicTagsResp, err error)
}

type AdminInsightsHTTPClientImpl struct {
	cc *http.Client
}

func NewAdminInsightsHTTPClient(client *http.Client) AdminInsightsHTTPClient {
	return &AdminInsightsHTTPClientImpl{client}
}

func (c *AdminInsightsHTTPClientImpl) AdminAnalyticsOverview(ctx context.Context, in *AdminGetMemoryStatsReq, opts ...http.CallOption) (*AdminAnalyticsOverviewResp, error) {
	var out AdminAnalyticsOverviewResp
	pattern := "/api/admin/analytics/overview"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminInsightsAdminAnalyticsOverview))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminInsightsHTTPClientImpl) AdminExportAiChatMessages(ctx context.Context, in *AdminExportAiChatMessagesReq, opts ...http.CallOption) (*AdminExportAiChatMessagesResp, error) {
	var out AdminExportAiChatMessagesResp
	pattern := "/api/admin/ai/chat/messages/export"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminInsightsAdminExportAiChatMessages))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminInsightsHTTPClientImpl) AdminListAiChatMessages(ctx context.Context, in *AdminListAiChatMessagesReq, opts ...http.CallOption) (*AdminListAiChatMessagesResp, error) {
	var out AdminListAiChatMessagesResp
	pattern := "/api/admin/ai/chat/messages"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminInsightsAdminListAiChatMessages))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminInsightsHTTPClientImpl) AdminListAiChatSessions(ctx context.Context, in *AdminListAiChatSessionsReq, opts ...http.CallOption) (*AdminListAiChatSessionsResp, error) {
	var out AdminListAiChatSessionsResp
	pattern := "/api/admin/ai/chat/sessions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminInsightsAdminListAiChatSessions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminInsightsHTTPClientImpl) AdminListTopicTags(ctx context.Context, in *AdminListTopicTagsReq, opts ...http.CallOption) (*AdminListTopicTagsResp, error) {
	var out AdminListTopicTagsResp
	pattern := "/api/admin/topic-tags"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminInsightsAdminListTopicTags))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
