// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: api/battle/v1/battle.proto

package battlev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BattleService_CreateRoom_FullMethodName     = "/battle.v1.BattleService/CreateRoom"
	BattleService_GetRoom_FullMethodName        = "/battle.v1.BattleService/GetRoom"
	BattleService_StartRoom_FullMethodName      = "/battle.v1.BattleService/StartRoom"
	BattleService_SendBattleGift_FullMethodName = "/battle.v1.BattleService/SendBattleGift"
	BattleService_FinishRoom_FullMethodName     = "/battle.v1.BattleService/FinishRoom"
)

// BattleServiceClient is the client API for BattleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BattleServiceClient interface {
	CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*BattleRoomReply, error)
	GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*BattleRoomReply, error)
	StartRoom(ctx context.Context, in *StartRoomRequest, opts ...grpc.CallOption) (*BattleRoomReply, error)
	SendBattleGift(ctx context.Context, in *SendBattleGiftRequest, opts ...grpc.CallOption) (*SendBattleGiftReply, error)
	FinishRoom(ctx context.Context, in *FinishRoomRequest, opts ...grpc.CallOption) (*BattleRoomReply, error)
}

type battleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBattleServiceClient(cc grpc.ClientConnInterface) BattleServiceClient {
	return &battleServiceClient{cc}
}

func (c *battleServiceClient) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*BattleRoomReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BattleRoomReply)
	err := c.cc.Invoke(ctx, BattleService_CreateRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceClient) GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*BattleRoomReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BattleRoomReply)
	err := c.cc.Invoke(ctx, BattleService_GetRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceClient) StartRoom(ctx context.Context, in *StartRoomRequest, opts ...grpc.CallOption) (*BattleRoomReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BattleRoomReply)
	err := c.cc.Invoke(ctx, BattleService_StartRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceClient) SendBattleGift(ctx context.Context, in *SendBattleGiftRequest, opts ...grpc.CallOption) (*SendBattleGiftReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendBattleGiftReply)
	err := c.cc.Invoke(ctx, BattleService_SendBattleGift_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceClient) FinishRoom(ctx context.Context, in *FinishRoomRequest, opts ...grpc.CallOption) (*BattleRoomReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BattleRoomReply)
	err := c.cc.Invoke(ctx, BattleService_FinishRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BattleServiceServer is the server API for BattleService service.
// All implementations must embed UnimplementedBattleServiceServer
// for forward compatibility.
type BattleServiceServer interface {
	CreateRoom(context.Context, *CreateRoomRequest) (*BattleRoomReply, error)
	GetRoom(context.Context, *GetRoomRequest) (*BattleRoomReply, error)
	StartRoom(context.Context, *StartRoomRequest) (*BattleRoomReply, error)
	SendBattleGift(context.Context, *SendBattleGiftRequest) (*SendBattleGiftReply, error)
	FinishRoom(context.Context, *FinishRoomRequest) (*BattleRoomReply, error)
	mustEmbedUnimplementedBattleServiceServer()
}

// UnimplementedBattleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBattleServiceServer struct{}

func (UnimplementedBattleServiceServer) CreateRoom(context.Context, *CreateRoomRequest) (*BattleRoomReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRoom not implemented")
}
func (UnimplementedBattleServiceServer) GetRoom(context.Context, *GetRoomRequest) (*BattleRoomReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoom not implemented")
}
func (UnimplementedBattleServiceServer) StartRoom(context.Context, *StartRoomRequest) (*BattleRoomReply, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRoom not implemented")
}
func (UnimplementedBattleServiceServer) SendBattleGift(context.Context, *SendBattleGiftRequest) (*SendBattleGiftReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SendBattleGift not implemented")
}
func (UnimplementedBattleServiceServer) FinishRoom(context.Context, *FinishRoomRequest) (*BattleRoomReply, error) {
	return nil, status.Error(codes.Unimplemented, "method FinishRoom not implemented")
}
func (UnimplementedBattleServiceServer) mustEmbedUnimplementedBattleServiceServer() {}
func (UnimplementedBattleServiceServer) testEmbeddedByValue()                       {}

// UnsafeBattleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BattleServiceServer will
// result in compilation errors.
type UnsafeBattleServiceServer interface {
	mustEmbedUnimplementedBattleServiceServer()
}

func RegisterBattleServiceServer(s grpc.ServiceRegistrar, srv BattleServiceServer) {
	// If the following call panics, it indicates UnimplementedBattleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BattleService_ServiceDesc, srv)
}

func _BattleService_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleService_CreateRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).CreateRoom(ctx, req.(*CreateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleService_GetRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).GetRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleService_GetRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).GetRoom(ctx, req.(*GetRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleService_StartRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).StartRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleService_StartRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).StartRoom(ctx, req.(*StartRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleService_SendBattleGift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendBattleGiftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).SendBattleGift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleService_SendBattleGift_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).SendBattleGift(ctx, req.(*SendBattleGiftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleService_FinishRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).FinishRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleService_FinishRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).FinishRoom(ctx, req.(*FinishRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BattleService_ServiceDesc is the grpc.ServiceDesc for BattleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BattleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "battle.v1.BattleService",
	HandlerType: (*BattleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoom",
			Handler:    _BattleService_CreateRoom_Handler,
		},
		{
			MethodName: "GetRoom",
			Handler:    _BattleService_GetRoom_Handler,
		},
		{
			MethodName: "StartRoom",
			Handler:    _BattleService_StartRoom_Handler,
		},
		{
			MethodName: "SendBattleGift",
			Handler:    _BattleService_SendBattleGift_Handler,
		},
		{
			MethodName: "FinishRoom",
			Handler:    _BattleService_FinishRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/battle/v1/battle.proto",
}
