// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: api/companion/v1/companion.proto

package companionv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCompanionConfirmMemory = "/companion.v1.Companion/ConfirmMemory"
const OperationCompanionDeleteMemory = "/companion.v1.Companion/DeleteMemory"
const OperationCompanionGetCommunityIdentity = "/companion.v1.Companion/GetCommunityIdentity"
const OperationCompanionGetContextPreview = "/companion.v1.Companion/GetContextPreview"
const OperationCompanionGetProactiveSettings = "/companion.v1.Companion/GetProactiveSettings"
const OperationCompanionGetProfile = "/companion.v1.Companion/GetProfile"
const OperationCompanionGetState = "/companion.v1.Companion/GetState"
const OperationCompanionGetTimeline = "/companion.v1.Companion/GetTimeline"
const OperationCompanionListChatHistory = "/companion.v1.Companion/ListChatHistory"
const OperationCompanionListEvents = "/companion.v1.Companion/ListEvents"
const OperationCompanionListMemories = "/companion.v1.Companion/ListMemories"
const OperationCompanionListMemoryConflicts = "/companion.v1.Companion/ListMemoryConflicts"
const OperationCompanionListProactiveDeliveries = "/companion.v1.Companion/ListProactiveDeliveries"
const OperationCompanionListRelationshipEvents = "/companion.v1.Companion/ListRelationshipEvents"
const OperationCompanionMarkProactiveRead = "/companion.v1.Companion/MarkProactiveRead"
const OperationCompanionResolveMemoryConflict = "/companion.v1.Companion/ResolveMemoryConflict"
const OperationCompanionRevokeProactiveDelivery = "/companion.v1.Companion/RevokeProactiveDelivery"
const OperationCompanionSetMemoryPinned = "/companion.v1.Companion/SetMemoryPinned"
const OperationCompanionUpdateMemory = "/companion.v1.Companion/UpdateMemory"
const OperationCompanionUpdateProactiveSettings = "/companion.v1.Companion/UpdateProactiveSettings"
const OperationCompanionUpsertProfile = "/companion.v1.Companion/UpsertProfile"

type CompanionHTTPServer interface {
	ConfirmMemory(context.Context, *ConfirmMemoryRequest) (*ConfirmMemoryReply, error)
	DeleteMemory(context.Context, *DeleteMemoryRequest) (*DeleteMemoryReply, error)
	GetCommunityIdentity(context.Context, *GetCommunityIdentityRequest) (*GetCommunityIdentityReply, error)
	GetContextPreview(context.Context, *ContextPreviewRequest) (*ContextPreviewReply, error)
	GetProactiveSettings(context.Context, *GetProactiveSettingsRequest) (*GetProactiveSettingsReply, error)
	// GetProfile Profile
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileReply, error)
	// GetState State（当前状态，含人格化表达 + 动态）
	GetState(context.Context, *GetStateRequest) (*GetStateReply, error)
	GetTimeline(context.Context, *ListEventsRequest) (*ListEventsReply, error)
	// ListChatHistory Chat History
	ListChatHistory(context.Context, *ListChatHistoryRequest) (*ListChatHistoryReply, error)
	ListEvents(context.Context, *ListEventsRequest) (*ListEventsReply, error)
	// ListMemories Memory
	ListMemories(context.Context, *ListMemoriesRequest) (*ListMemoriesReply, error)
	ListMemoryConflicts(context.Context, *ListMemoryConflictsRequest) (*ListMemoryConflictsReply, error)
	ListProactiveDeliveries(context.Context, *ListProactiveDeliveriesRequest) (*ListProactiveDeliveriesReply, error)
	ListRelationshipEvents(context.Context, *ListRelationshipEventsRequest) (*ListRelationshipEventsReply, error)
	MarkProactiveRead(context.Context, *MarkProactiveReadRequest) (*MarkProactiveReadReply, error)
	ResolveMemoryConflict(context.Context, *ResolveMemoryConflictRequest) (*ResolveMemoryConflictReply, error)
	RevokeProactiveDelivery(context.Context, *RevokeProactiveDeliveryRequest) (*RevokeProactiveDeliveryReply, error)
	SetMemoryPinned(context.Context, *SetMemoryPinnedRequest) (*SetMemoryPinnedReply, error)
	UpdateMemory(context.Context, *UpdateMemoryRequest) (*UpdateMemoryReply, error)
	UpdateProactiveSettings(context.Context, *UpdateProactiveSettingsRequest) (*UpdateProactiveSettingsReply, error)
	UpsertProfile(context.Context, *UpsertProfileRequest) (*UpsertProfileReply, error)
}

func RegisterCompanionHTTPServer(s *http.Server, srv CompanionHTTPServer) {
	r := s.Route("/")
	r.GET("/api/companion/profile", _Companion_GetProfile0_HTTP_Handler(srv))
	r.GET("/api/companion/community-identity", _Companion_GetCommunityIdentity0_HTTP_Handler(srv))
	r.POST("/api/companion/profile", _Companion_UpsertProfile0_HTTP_Handler(srv))
	r.GET("/api/companion/state", _Companion_GetState0_HTTP_Handler(srv))
	r.GET("/api/companion/memories", _Companion_ListMemories0_HTTP_Handler(srv))
	r.DELETE("/api/companion/memories/{memory_id}", _Companion_DeleteMemory0_HTTP_Handler(srv))
	r.POST("/api/companion/memories/{memory_id}/pin", _Companion_SetMemoryPinned0_HTTP_Handler(srv))
	r.PUT("/api/companion/memories/{memory_id}", _Companion_UpdateMemory0_HTTP_Handler(srv))
	r.GET("/api/companion/chat/history", _Companion_ListChatHistory0_HTTP_Handler(srv))
	r.GET("/api/companion/proactive-settings", _Companion_GetProactiveSettings0_HTTP_Handler(srv))
	r.PUT("/api/companion/proactive-settings", _Companion_UpdateProactiveSettings0_HTTP_Handler(srv))
	r.POST("/api/companion/memories/{memory_id}/confirm", _Companion_ConfirmMemory0_HTTP_Handler(srv))
	r.GET("/api/companion/memory-conflicts", _Companion_ListMemoryConflicts0_HTTP_Handler(srv))
	r.POST("/api/companion/memory-conflicts/{conflict_id}/resolve", _Companion_ResolveMemoryConflict0_HTTP_Handler(srv))
	r.GET("/api/companion/relationship-events", _Companion_ListRelationshipEvents0_HTTP_Handler(srv))
	r.GET("/api/companion/events", _Companion_ListEvents0_HTTP_Handler(srv))
	r.GET("/api/companion/timeline", _Companion_GetTimeline0_HTTP_Handler(srv))
	r.GET("/api/companion/context/preview", _Companion_GetContextPreview0_HTTP_Handler(srv))
	r.GET("/api/companion/proactive-deliveries", _Companion_ListProactiveDeliveries0_HTTP_Handler(srv))
	r.POST("/api/companion/proactive/revoke", _Companion_RevokeProactiveDelivery0_HTTP_Handler(srv))
	r.POST("/api/companion/proactive/{notification_id}/read", _Companion_MarkProactiveRead0_HTTP_Handler(srv))
}

func _Companion_GetProfile0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProfileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionGetProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProfile(ctx, req.(*GetProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetProfileReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_GetCommunityIdentity0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCommunityIdentityRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionGetCommunityIdentity)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCommunityIdentity(ctx, req.(*GetCommunityIdentityRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCommunityIdentityReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_UpsertProfile0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpsertProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionUpsertProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpsertProfile(ctx, req.(*UpsertProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpsertProfileReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_GetState0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetStateRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionGetState)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetState(ctx, req.(*GetStateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetStateReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_ListMemories0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMemoriesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionListMemories)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMemories(ctx, req.(*ListMemoriesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMemoriesReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_DeleteMemory0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteMemoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionDeleteMemory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteMemory(ctx, req.(*DeleteMemoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteMemoryReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_SetMemoryPinned0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetMemoryPinnedRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionSetMemoryPinned)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetMemoryPinned(ctx, req.(*SetMemoryPinnedRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetMemoryPinnedReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_UpdateMemory0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateMemoryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionUpdateMemory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateMemory(ctx, req.(*UpdateMemoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateMemoryReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_ListChatHistory0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListChatHistoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionListChatHistory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListChatHistory(ctx, req.(*ListChatHistoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListChatHistoryReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_GetProactiveSettings0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProactiveSettingsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionGetProactiveSettings)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProactiveSettings(ctx, req.(*GetProactiveSettingsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetProactiveSettingsReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_UpdateProactiveSettings0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProactiveSettingsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionUpdateProactiveSettings)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProactiveSettings(ctx, req.(*UpdateProactiveSettingsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateProactiveSettingsReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_ConfirmMemory0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ConfirmMemoryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionConfirmMemory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ConfirmMemory(ctx, req.(*ConfirmMemoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConfirmMemoryReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_ListMemoryConflicts0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMemoryConflictsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionListMemoryConflicts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMemoryConflicts(ctx, req.(*ListMemoryConflictsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMemoryConflictsReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_ResolveMemoryConflict0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ResolveMemoryConflictRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionResolveMemoryConflict)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ResolveMemoryConflict(ctx, req.(*ResolveMemoryConflictRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ResolveMemoryConflictReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_ListRelationshipEvents0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRelationshipEventsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionListRelationshipEvents)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRelationshipEvents(ctx, req.(*ListRelationshipEventsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRelationshipEventsReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_ListEvents0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListEventsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionListEvents)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEvents(ctx, req.(*ListEventsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListEventsReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_GetTimeline0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListEventsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionGetTimeline)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTimeline(ctx, req.(*ListEventsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListEventsReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_GetContextPreview0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ContextPreviewRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionGetContextPreview)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetContextPreview(ctx, req.(*ContextPreviewRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ContextPreviewReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_ListProactiveDeliveries0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProactiveDeliveriesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionListProactiveDeliveries)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProactiveDeliveries(ctx, req.(*ListProactiveDeliveriesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProactiveDeliveriesReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_RevokeProactiveDelivery0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RevokeProactiveDeliveryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionRevokeProactiveDelivery)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RevokeProactiveDelivery(ctx, req.(*RevokeProactiveDeliveryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RevokeProactiveDeliveryReply)
		return ctx.Result(200, reply)
	}
}

func _Companion_MarkProactiveRead0_HTTP_Handler(srv CompanionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MarkProactiveReadRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCompanionMarkProactiveRead)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MarkProactiveRead(ctx, req.(*MarkProactiveReadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MarkProactiveReadReply)
		return ctx.Result(200, reply)
	}
}

type CompanionHTTPClient interface {
	ConfirmMemory(ctx context.Context, req *ConfirmMemoryRequest, opts ...http.CallOption) (rsp *ConfirmMemoryReply, err error)
	DeleteMemory(ctx context.Context, req *DeleteMemoryRequest, opts ...http.CallOption) (rsp *DeleteMemoryReply, err error)
	GetCommunityIdentity(ctx context.Context, req *GetCommunityIdentityRequest, opts ...http.CallOption) (rsp *GetCommunityIdentityReply, err error)
	GetContextPreview(ctx context.Context, req *ContextPreviewRequest, opts ...http.CallOption) (rsp *ContextPreviewReply, err error)
	GetProactiveSettings(ctx context.Context, req *GetProactiveSettingsRequest, opts ...http.CallOption) (rsp *GetProactiveSettingsReply, err error)
	// GetProfile Profile
	GetProfile(ctx context.Context, req *GetProfileRequest, opts ...http.CallOption) (rsp *GetProfileReply, err error)
	// GetState State（当前状态，含人格化表达 + 动态）
	GetState(ctx context.Context, req *GetStateRequest, opts ...http.CallOption) (rsp *GetStateReply, err error)
	GetTimeline(ctx context.Context, req *ListEventsRequest, opts ...http.CallOption) (rsp *ListEventsReply, err error)
	// ListChatHistory Chat History
	ListChatHistory(ctx context.Context, req *ListChatHistoryRequest, opts ...http.CallOption) (rsp *ListChatHistoryReply, err error)
	ListEvents(ctx context.Context, req *ListEventsRequest, opts ...http.CallOption) (rsp *ListEventsReply, err error)
	// ListMemories Memory
	ListMemories(ctx context.Context, req *ListMemoriesRequest, opts ...http.CallOption) (rsp *ListMemoriesReply, err error)
	ListMemoryConflicts(ctx context.Context, req *ListMemoryConflictsRequest, opts ...http.CallOption) (rsp *ListMemoryConflictsReply, err error)
	ListProactiveDeliveries(ctx context.Context, req *ListProactiveDeliveriesRequest, opts ...http.CallOption) (rsp *ListProactiveDeliveriesReply, err error)
	ListRelationshipEvents(ctx context.Context, req *ListRelationshipEventsRequest, opts ...http.CallOption) (rsp *ListRelationshipEventsReply, err error)
	MarkProactiveRead(ctx context.Context, req *MarkProactiveReadRequest, opts ...http.CallOption) (rsp *MarkProactiveReadReply, err error)
	ResolveMemoryConflict(ctx context.Context, req *ResolveMemoryConflictRequest, opts ...http.CallOption) (rsp *ResolveMemoryConflictReply, err error)
	RevokeProactiveDelivery(ctx context.Context, req *RevokeProactiveDeliveryRequest, opts ...http.CallOption) (rsp *RevokeProactiveDeliveryReply, err error)
	SetMemoryPinned(ctx context.Context, req *SetMemoryPinnedRequest, opts ...http.CallOption) (rsp *SetMemoryPinnedReply, err error)
	UpdateMemory(ctx context.Context, req *UpdateMemoryRequest, opts ...http.CallOption) (rsp *UpdateMemoryReply, err error)
	UpdateProactiveSettings(ctx context.Context, req *UpdateProactiveSettingsRequest, opts ...http.CallOption) (rsp *UpdateProactiveSettingsReply, err error)
	UpsertProfile(ctx context.Context, req *UpsertProfileRequest, opts ...http.CallOption) (rsp *UpsertProfileReply, err error)
}

type CompanionHTTPClientImpl struct {
	cc *http.Client
}

func NewCompanionHTTPClient(client *http.Client) CompanionHTTPClient {
	return &CompanionHTTPClientImpl{client}
}

func (c *CompanionHTTPClientImpl) ConfirmMemory(ctx context.Context, in *ConfirmMemoryRequest, opts ...http.CallOption) (*ConfirmMemoryReply, error) {
	var out ConfirmMemoryReply
	pattern := "/api/companion/memories/{memory_id}/confirm"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCompanionConfirmMemory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) DeleteMemory(ctx context.Context, in *DeleteMemoryRequest, opts ...http.CallOption) (*DeleteMemoryReply, error) {
	var out DeleteMemoryReply
	pattern := "/api/companion/memories/{memory_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCompanionDeleteMemory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) GetCommunityIdentity(ctx context.Context, in *GetCommunityIdentityRequest, opts ...http.CallOption) (*GetCommunityIdentityReply, error) {
	var out GetCommunityIdentityReply
	pattern := "/api/companion/community-identity"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCompanionGetCommunityIdentity))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) GetContextPreview(ctx context.Context, in *ContextPreviewRequest, opts ...http.CallOption) (*ContextPreviewReply, error) {
	var out ContextPreviewReply
	pattern := "/api/companion/context/preview"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCompanionGetContextPreview))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) GetProactiveSettings(ctx context.Context, in *GetProactiveSettingsRequest, opts ...http.CallOption) (*GetProactiveSettingsReply, error) {
	var out GetProactiveSettingsReply
	pattern := "/api/companion/proactive-settings"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCompanionGetProactiveSettings))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetProfile Profile
func (c *CompanionHTTPClientImpl) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...http.CallOption) (*GetProfileReply, error) {
	var out GetProfileReply
	pattern := "/api/companion/profile"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCompanionGetProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetState State（当前状态，含人格化表达 + 动态）
func (c *CompanionHTTPClientImpl) GetState(ctx context.Context, in *GetStateRequest, opts ...http.CallOption) (*GetStateReply, error) {
	var out GetStateReply
	pattern := "/api/companion/state"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCompanionGetState))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) GetTimeline(ctx context.Context, in *ListEventsRequest, opts ...http.CallOption) (*ListEventsReply, error) {
	var out ListEventsReply
	pattern := "/api/companion/timeline"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCompanionGetTimeline))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListChatHistory Chat History
func (c *CompanionHTTPClientImpl) ListChatHistory(ctx context.Context, in *ListChatHistoryRequest, opts ...http.CallOption) (*ListChatHistoryReply, error) {
	var out ListChatHistoryReply
	pattern := "/api/companion/chat/history"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCompanionListChatHistory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...http.CallOption) (*ListEventsReply, error) {
	var out ListEventsReply
	pattern := "/api/companion/events"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCompanionListEvents))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListMemories Memory
func (c *CompanionHTTPClientImpl) ListMemories(ctx context.Context, in *ListMemoriesRequest, opts ...http.CallOption) (*ListMemoriesReply, error) {
	var out ListMemoriesReply
	pattern := "/api/companion/memories"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCompanionListMemories))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) ListMemoryConflicts(ctx context.Context, in *ListMemoryConflictsRequest, opts ...http.CallOption) (*ListMemoryConflictsReply, error) {
	var out ListMemoryConflictsReply
	pattern := "/api/companion/memory-conflicts"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCompanionListMemoryConflicts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) ListProactiveDeliveries(ctx context.Context, in *ListProactiveDeliveriesRequest, opts ...http.CallOption) (*ListProactiveDeliveriesReply, error) {
	var out ListProactiveDeliveriesReply
	pattern := "/api/companion/proactive-deliveries"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCompanionListProactiveDeliveries))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) ListRelationshipEvents(ctx context.Context, in *ListRelationshipEventsRequest, opts ...http.CallOption) (*ListRelationshipEventsReply, error) {
	var out ListRelationshipEventsReply
	pattern := "/api/companion/relationship-events"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCompanionListRelationshipEvents))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) MarkProactiveRead(ctx context.Context, in *MarkProactiveReadRequest, opts ...http.CallOption) (*MarkProactiveReadReply, error) {
	var out MarkProactiveReadReply
	pattern := "/api/companion/proactive/{notification_id}/read"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCompanionMarkProactiveRead))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) ResolveMemoryConflict(ctx context.Context, in *ResolveMemoryConflictRequest, opts ...http.CallOption) (*ResolveMemoryConflictReply, error) {
	var out ResolveMemoryConflictReply
	pattern := "/api/companion/memory-conflicts/{conflict_id}/resolve"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCompanionResolveMemoryConflict))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) RevokeProactiveDelivery(ctx context.Context, in *RevokeProactiveDeliveryRequest, opts ...http.CallOption) (*RevokeProactiveDeliveryReply, error) {
	var out RevokeProactiveDeliveryReply
	pattern := "/api/companion/proactive/revoke"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCompanionRevokeProactiveDelivery))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) SetMemoryPinned(ctx context.Context, in *SetMemoryPinnedRequest, opts ...http.CallOption) (*SetMemoryPinnedReply, error) {
	var out SetMemoryPinnedReply
	pattern := "/api/companion/memories/{memory_id}/pin"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCompanionSetMemoryPinned))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) UpdateMemory(ctx context.Context, in *UpdateMemoryRequest, opts ...http.CallOption) (*UpdateMemoryReply, error) {
	var out UpdateMemoryReply
	pattern := "/api/companion/memories/{memory_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCompanionUpdateMemory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) UpdateProactiveSettings(ctx context.Context, in *UpdateProactiveSettingsRequest, opts ...http.CallOption) (*UpdateProactiveSettingsReply, error) {
	var out UpdateProactiveSettingsReply
	pattern := "/api/companion/proactive-settings"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCompanionUpdateProactiveSettings))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CompanionHTTPClientImpl) UpsertProfile(ctx context.Context, in *UpsertProfileRequest, opts ...http.CallOption) (*UpsertProfileReply, error) {
	var out UpsertProfileReply
	pattern := "/api/companion/profile"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCompanionUpsertProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
