// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: api/user/v1/user.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username               string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                  string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Avatar                 string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Signature              string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	Gender                 string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthday               string                 `protobuf:"bytes,7,opt,name=birthday,proto3" json:"birthday,omitempty"`
	CreatedAt              string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt              string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsVip                  bool                   `protobuf:"varint,10,opt,name=is_vip,json=isVip,proto3" json:"is_vip,omitempty"`
	VipExpiresAt           string                 `protobuf:"bytes,11,opt,name=vip_expires_at,json=vipExpiresAt,proto3" json:"vip_expires_at,omitempty"`
	AutoRenew              bool                   `protobuf:"varint,12,opt,name=auto_renew,json=autoRenew,proto3" json:"auto_renew,omitempty"`
	Balance                float32                `protobuf:"fixed32,13,opt,name=balance,proto3" json:"balance,omitempty"`
	Inventory              string                 `protobuf:"bytes,14,opt,name=inventory,proto3" json:"inventory,omitempty"`
	EquippedFrameId        string                 `protobuf:"bytes,15,opt,name=equipped_frame_id,json=equippedFrameId,proto3" json:"equipped_frame_id,omitempty"`
	MoeNo                  string                 `protobuf:"bytes,16,opt,name=moe_no,json=moeNo,proto3" json:"moe_no,omitempty"`
	GiftCharm              int32                  `protobuf:"varint,17,opt,name=gift_charm,json=giftCharm,proto3" json:"gift_charm,omitempty"`
	ReceivedGiftValue      float64                `protobuf:"fixed64,18,opt,name=received_gift_value,json=receivedGiftValue,proto3" json:"received_gift_value,omitempty"`
	DisplayUserId          string                 `protobuf:"bytes,19,opt,name=display_user_id,json=displayUserId,proto3" json:"display_user_id,omitempty"`
	MessageRetentionChoice int32                  `protobuf:"varint,20,opt,name=message_retention_choice,json=messageRetentionChoice,proto3" json:"message_retention_choice,omitempty"`
	FeishuEmail            string                 `protobuf:"bytes,21,opt,name=feishu_email,json=feishuEmail,proto3" json:"feishu_email,omitempty"`
	FeishuName             string                 `protobuf:"bytes,22,opt,name=feishu_name,json=feishuName,proto3" json:"feishu_name,omitempty"`
	FeishuBound            bool                   `protobuf:"varint,23,opt,name=feishu_bound,json=feishuBound,proto3" json:"feishu_bound,omitempty"`
	Role                   string                 `protobuf:"bytes,24,opt,name=role,proto3" json:"role,omitempty"`
	WechatNickname         string                 `protobuf:"bytes,25,opt,name=wechat_nickname,json=wechatNickname,proto3" json:"wechat_nickname,omitempty"`
	WechatBound            bool                   `protobuf:"varint,26,opt,name=wechat_bound,json=wechatBound,proto3" json:"wechat_bound,omitempty"`
	IsBot                  bool                   `protobuf:"varint,27,opt,name=is_bot,json=isBot,proto3" json:"is_bot,omitempty"`
	BotAgentKey            string                 `protobuf:"bytes,28,opt,name=bot_agent_key,json=botAgentKey,proto3" json:"bot_agent_key,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *User) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *User) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *User) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *User) GetIsVip() bool {
	if x != nil {
		return x.IsVip
	}
	return false
}

func (x *User) GetVipExpiresAt() string {
	if x != nil {
		return x.VipExpiresAt
	}
	return ""
}

func (x *User) GetAutoRenew() bool {
	if x != nil {
		return x.AutoRenew
	}
	return false
}

func (x *User) GetBalance() float32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *User) GetInventory() string {
	if x != nil {
		return x.Inventory
	}
	return ""
}

func (x *User) GetEquippedFrameId() string {
	if x != nil {
		return x.EquippedFrameId
	}
	return ""
}

func (x *User) GetMoeNo() string {
	if x != nil {
		return x.MoeNo
	}
	return ""
}

func (x *User) GetGiftCharm() int32 {
	if x != nil {
		return x.GiftCharm
	}
	return 0
}

func (x *User) GetReceivedGiftValue() float64 {
	if x != nil {
		return x.ReceivedGiftValue
	}
	return 0
}

func (x *User) GetDisplayUserId() string {
	if x != nil {
		return x.DisplayUserId
	}
	return ""
}

func (x *User) GetMessageRetentionChoice() int32 {
	if x != nil {
		return x.MessageRetentionChoice
	}
	return 0
}

func (x *User) GetFeishuEmail() string {
	if x != nil {
		return x.FeishuEmail
	}
	return ""
}

func (x *User) GetFeishuName() string {
	if x != nil {
		return x.FeishuName
	}
	return ""
}

func (x *User) GetFeishuBound() bool {
	if x != nil {
		return x.FeishuBound
	}
	return false
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetWechatNickname() string {
	if x != nil {
		return x.WechatNickname
	}
	return ""
}

func (x *User) GetWechatBound() bool {
	if x != nil {
		return x.WechatBound
	}
	return false
}

func (x *User) GetIsBot() bool {
	if x != nil {
		return x.IsBot
	}
	return false
}

func (x *User) GetBotAgentKey() string {
	if x != nil {
		return x.BotAgentKey
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_api_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *LoginReply) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_api_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterReply) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RegisterReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReply) Reset() {
	*x = GetUserInfoReply{}
	mi := &file_api_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReply) ProtoMessage() {}

func (x *GetUserInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReply.ProtoReflect.Descriptor instead.
func (*GetUserInfoReply) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserInfoReply) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReply) Reset() {
	*x = GetUserReply{}
	mi := &file_api_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReply) ProtoMessage() {}

func (x *GetUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReply.ProtoReflect.Descriptor instead.
func (*GetUserReply) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserReply) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserInfoRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username           string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email              string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Avatar             string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Signature          string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	Gender             string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthday           string                 `protobuf:"bytes,7,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Inventory          string                 `protobuf:"bytes,8,opt,name=inventory,proto3" json:"inventory,omitempty"`
	EquippedFrameId    string                 `protobuf:"bytes,9,opt,name=equipped_frame_id,json=equippedFrameId,proto3" json:"equipped_frame_id,omitempty"`
	ClearEquippedFrame bool                   `protobuf:"varint,10,opt,name=clear_equipped_frame,json=clearEquippedFrame,proto3" json:"clear_equipped_frame,omitempty"`
	MessageRetention   string                 `protobuf:"bytes,11,opt,name=message_retention,json=messageRetention,proto3" json:"message_retention,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateUserInfoRequest) Reset() {
	*x = UpdateUserInfoRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoRequest) ProtoMessage() {}

func (x *UpdateUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateUserInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetInventory() string {
	if x != nil {
		return x.Inventory
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetEquippedFrameId() string {
	if x != nil {
		return x.EquippedFrameId
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetClearEquippedFrame() bool {
	if x != nil {
		return x.ClearEquippedFrame
	}
	return false
}

func (x *UpdateUserInfoRequest) GetMessageRetention() string {
	if x != nil {
		return x.MessageRetention
	}
	return ""
}

type UpdateUserInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoReply) Reset() {
	*x = UpdateUserInfoReply{}
	mi := &file_api_user_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoReply) ProtoMessage() {}

func (x *UpdateUserInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoReply.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoReply) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateUserInfoReply) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_api_user_v1_user_proto protoreflect.FileDescriptor

const file_api_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x16api/user/v1/user.proto\x12\auser.v1\"\xfa\x06\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\x12\x1a\n" +
	"\bbirthday\x18\a \x01(\tR\bbirthday\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12\x15\n" +
	"\x06is_vip\x18\n" +
	" \x01(\bR\x05isVip\x12$\n" +
	"\x0evip_expires_at\x18\v \x01(\tR\fvipExpiresAt\x12\x1d\n" +
	"\n" +
	"auto_renew\x18\f \x01(\bR\tautoRenew\x12\x18\n" +
	"\abalance\x18\r \x01(\x02R\abalance\x12\x1c\n" +
	"\tinventory\x18\x0e \x01(\tR\tinventory\x12*\n" +
	"\x11equipped_frame_id\x18\x0f \x01(\tR\x0fequippedFrameId\x12\x15\n" +
	"\x06moe_no\x18\x10 \x01(\tR\x05moeNo\x12\x1d\n" +
	"\n" +
	"gift_charm\x18\x11 \x01(\x05R\tgiftCharm\x12.\n" +
	"\x13received_gift_value\x18\x12 \x01(\x01R\x11receivedGiftValue\x12&\n" +
	"\x0fdisplay_user_id\x18\x13 \x01(\tR\rdisplayUserId\x128\n" +
	"\x18message_retention_choice\x18\x14 \x01(\x05R\x16messageRetentionChoice\x12!\n" +
	"\ffeishu_email\x18\x15 \x01(\tR\vfeishuEmail\x12\x1f\n" +
	"\vfeishu_name\x18\x16 \x01(\tR\n" +
	"feishuName\x12!\n" +
	"\ffeishu_bound\x18\x17 \x01(\bR\vfeishuBound\x12\x12\n" +
	"\x04role\x18\x18 \x01(\tR\x04role\x12'\n" +
	"\x0fwechat_nickname\x18\x19 \x01(\tR\x0ewechatNickname\x12!\n" +
	"\fwechat_bound\x18\x1a \x01(\bR\vwechatBound\x12\x15\n" +
	"\x06is_bot\x18\x1b \x01(\bR\x05isBot\x12\"\n" +
	"\rbot_agent_key\x18\x1c \x01(\tR\vbotAgentKey\"\\\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"E\n" +
	"\n" +
	"LoginReply\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"_\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"H\n" +
	"\rRegisterReply\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"-\n" +
	"\x12GetUserInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"5\n" +
	"\x10GetUserInfoReply\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"1\n" +
	"\fGetUserReply\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\"\xf5\x02\n" +
	"\x15UpdateUserInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\x12\x1a\n" +
	"\bbirthday\x18\a \x01(\tR\bbirthday\x12\x1c\n" +
	"\tinventory\x18\b \x01(\tR\tinventory\x12*\n" +
	"\x11equipped_frame_id\x18\t \x01(\tR\x0fequippedFrameId\x120\n" +
	"\x14clear_equipped_frame\x18\n" +
	" \x01(\bR\x12clearEquippedFrame\x12+\n" +
	"\x11message_retention\x18\v \x01(\tR\x10messageRetention\"8\n" +
	"\x13UpdateUserInfoReply\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user2\xd2\x02\n" +
	"\vUserService\x123\n" +
	"\x05Login\x12\x15.user.v1.LoginRequest\x1a\x13.user.v1.LoginReply\x12<\n" +
	"\bRegister\x12\x18.user.v1.RegisterRequest\x1a\x16.user.v1.RegisterReply\x12E\n" +
	"\vGetUserInfo\x12\x1b.user.v1.GetUserInfoRequest\x1a\x19.user.v1.GetUserInfoReply\x129\n" +
	"\aGetUser\x12\x17.user.v1.GetUserRequest\x1a\x15.user.v1.GetUserReply\x12N\n" +
	"\x0eUpdateUserInfo\x12\x1e.user.v1.UpdateUserInfoRequest\x1a\x1c.user.v1.UpdateUserInfoReplyB\x1cZ\x1abackend/api/user/v1;userv1b\x06proto3"

var (
	file_api_user_v1_user_proto_rawDescOnce sync.Once
	file_api_user_v1_user_proto_rawDescData []byte
)

func file_api_user_v1_user_proto_rawDescGZIP() []byte {
	file_api_user_v1_user_proto_rawDescOnce.Do(func() {
		file_api_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_v1_user_proto_rawDesc), len(file_api_user_v1_user_proto_rawDesc)))
	})
	return file_api_user_v1_user_proto_rawDescData
}

var file_api_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_user_v1_user_proto_goTypes = []any{
	(*User)(nil),                  // 0: user.v1.User
	(*LoginRequest)(nil),          // 1: user.v1.LoginRequest
	(*LoginReply)(nil),            // 2: user.v1.LoginReply
	(*RegisterRequest)(nil),       // 3: user.v1.RegisterRequest
	(*RegisterReply)(nil),         // 4: user.v1.RegisterReply
	(*GetUserInfoRequest)(nil),    // 5: user.v1.GetUserInfoRequest
	(*GetUserInfoReply)(nil),      // 6: user.v1.GetUserInfoReply
	(*GetUserRequest)(nil),        // 7: user.v1.GetUserRequest
	(*GetUserReply)(nil),          // 8: user.v1.GetUserReply
	(*UpdateUserInfoRequest)(nil), // 9: user.v1.UpdateUserInfoRequest
	(*UpdateUserInfoReply)(nil),   // 10: user.v1.UpdateUserInfoReply
}
var file_api_user_v1_user_proto_depIdxs = []int32{
	0,  // 0: user.v1.LoginReply.user:type_name -> user.v1.User
	0,  // 1: user.v1.RegisterReply.user:type_name -> user.v1.User
	0,  // 2: user.v1.GetUserInfoReply.user:type_name -> user.v1.User
	0,  // 3: user.v1.GetUserReply.user:type_name -> user.v1.User
	0,  // 4: user.v1.UpdateUserInfoReply.user:type_name -> user.v1.User
	1,  // 5: user.v1.UserService.Login:input_type -> user.v1.LoginRequest
	3,  // 6: user.v1.UserService.Register:input_type -> user.v1.RegisterRequest
	5,  // 7: user.v1.UserService.GetUserInfo:input_type -> user.v1.GetUserInfoRequest
	7,  // 8: user.v1.UserService.GetUser:input_type -> user.v1.GetUserRequest
	9,  // 9: user.v1.UserService.UpdateUserInfo:input_type -> user.v1.UpdateUserInfoRequest
	2,  // 10: user.v1.UserService.Login:output_type -> user.v1.LoginReply
	4,  // 11: user.v1.UserService.Register:output_type -> user.v1.RegisterReply
	6,  // 12: user.v1.UserService.GetUserInfo:output_type -> user.v1.GetUserInfoReply
	8,  // 13: user.v1.UserService.GetUser:output_type -> user.v1.GetUserReply
	10, // 14: user.v1.UserService.UpdateUserInfo:output_type -> user.v1.UpdateUserInfoReply
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_user_v1_user_proto_init() }
func file_api_user_v1_user_proto_init() {
	if File_api_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_v1_user_proto_rawDesc), len(file_api_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_user_v1_user_proto_goTypes,
		DependencyIndexes: file_api_user_v1_user_proto_depIdxs,
		MessageInfos:      file_api_user_v1_user_proto_msgTypes,
	}.Build()
	File_api_user_v1_user_proto = out.File
	file_api_user_v1_user_proto_goTypes = nil
	file_api_user_v1_user_proto_depIdxs = nil
}
