package utils

import "backend/model"

// MigrateEntry describes one model that should participate in AutoMigrate.
type MigrateEntry struct {
	Key   string
	Model interface{}
}

// MigrateModelRegistry keeps the AutoMigrate list in one place.
func MigrateModelRegistry() []MigrateEntry {
	return []MigrateEntry{
		{Key: "users", Model: &model.User{}},
		{Key: "vip_plans", Model: &model.VipPlan{}},
		{Key: "vip_orders", Model: &model.VipOrder{}},
		{Key: "vip_records", Model: &model.VipRecord{}},
		{Key: "transactions", Model: &model.Transaction{}},
		{Key: "posts", Model: &model.Post{}},
		{Key: "post_reports", Model: &model.PostReport{}},
		{Key: "likes", Model: &model.Like{}},
		{Key: "topic_tags", Model: &model.TopicTag{}},
		{Key: "post_topics", Model: &model.PostTopic{}},
		{Key: "comments", Model: &model.Comment{}},
		{Key: "follows", Model: &model.Follow{}},
		{Key: "notifications", Model: &model.Notification{}},
		{Key: "user_avatars", Model: &model.UserAvatar{}},
		{Key: "avatar_pack_revisions", Model: &model.AvatarPackRevision{}},
		{Key: "avatar_outfits", Model: &model.AvatarOutfit{}},
		{Key: "emojis", Model: &model.Emoji{}},
		{Key: "emoji_packs", Model: &model.EmojiPack{}},
		{Key: "user_emoji_packs", Model: &model.UserEmojiPack{}},
		{Key: "user_devices", Model: &model.UserDevice{}},
		{Key: "ai_user_configs", Model: &model.AiUserConfig{}},
		{Key: "user_levels", Model: &model.UserLevel{}},
		{Key: "level_configs", Model: &model.LevelConfig{}},
		{Key: "user_check_ins", Model: &model.UserCheckIn{}},
		{Key: "check_in_rewards", Model: &model.CheckInReward{}},
		{Key: "exp_logs", Model: &model.ExpLog{}},
		{Key: "achievement_definitions", Model: &model.AchievementDefinition{}},
		{Key: "user_achievement_progress", Model: &model.UserAchievementProgress{}},
		{Key: "user_daily_activities", Model: &model.UserDailyActivity{}},
		{Key: "user_weekly_activities", Model: &model.UserWeeklyActivity{}},
		{Key: "friend_requests", Model: &model.FriendRequest{}},
		{Key: "gifts", Model: &model.Gift{}},
		{Key: "gift_records", Model: &model.GiftRecord{}},
		{Key: "user_gift_stocks", Model: &model.UserGiftStock{}},
		{Key: "gift_purchase_orders", Model: &model.GiftPurchaseOrder{}},
		{Key: "groups", Model: &model.Group{}},
		{Key: "group_members", Model: &model.GroupMember{}},
		{Key: "group_posts", Model: &model.GroupPost{}},
		{Key: "private_messages", Model: &model.PrivateMessage{}},
		{Key: "landing_feedbacks", Model: &model.LandingFeedback{}},
		{Key: "admin_accounts", Model: &model.AdminAccount{}},
		{Key: "admin_announcements", Model: &model.AdminAnnouncement{}},
		{Key: "app_releases", Model: &model.AppRelease{}},
		{Key: "admin_menus", Model: &model.AdminMenu{}},
		{Key: "admin_audit_logs", Model: &model.AdminAuditLog{}},
		{Key: "user_behavior_events", Model: &model.UserBehaviorEvent{}},
		{Key: "user_behavior_daily", Model: &model.UserBehaviorDaily{}},
		{Key: "moe_agent_runtimes", Model: &model.MoeAgentRuntime{}},
		{Key: "moe_bot_episodes", Model: &model.MoeBotEpisode{}},
		{Key: "moe_agent_topic_stats", Model: &model.MoeAgentTopicStat{}},
		{Key: "moe_tool_calls", Model: &model.MoeToolCall{}},
		{Key: "moe_agent_run_logs", Model: &model.MoeAgentRunLog{}},
		{Key: "moe_agent_flow_configs", Model: &model.MoeAgentFlowConfig{}},
		{Key: "moe_brain_dream_logs", Model: &model.MoeBrainDreamLog{}},
		{Key: "ai_chat_sessions", Model: &model.AiChatSession{}},
		{Key: "ai_chat_messages", Model: &model.AiChatMessage{}},
		{Key: "game_sessions", Model: &model.GameSession{}},
		{Key: "game_scenes", Model: &model.GameScene{}},
		{Key: "game_npcs", Model: &model.GameNpc{}},
		{Key: "game_npc_memories", Model: &model.GameNpcMemory{}},
		{Key: "game_turn_logs", Model: &model.GameTurnLog{}},
		{Key: "game_world_items", Model: &model.GameWorldItem{}},
		{Key: "game_npc_templates", Model: &model.GameNpcTemplate{}},
		{Key: "game_save_slots", Model: &model.GameSaveSlot{}},
		{Key: "game_dialogue_templates", Model: &model.GameDialogueTemplate{}},
		{Key: "game_story_arcs", Model: &model.GameStoryArc{}},
		{Key: "game_world_states", Model: &model.GameWorldState{}},
		{Key: "game_discovered_items", Model: &model.GameDiscoveredItem{}},
		{Key: "game_visited_scenes", Model: &model.GameVisitedScene{}},
		{Key: "game_npc_activities", Model: &model.GameNpcActivity{}},
		{Key: "game_world_events", Model: &model.GameWorldEvent{}},
		{Key: "tag_dictionary_entries", Model: &model.TagDictionaryEntry{}},
		{Key: "life_entities", Model: &model.LifeEntity{}},
		{Key: "life_worlds", Model: &model.LifeWorld{}},
		{Key: "life_event_logs", Model: &model.LifeEventLog{}},
		{Key: "life_relationships", Model: &model.LifeRelationship{}},
		{Key: "life_items", Model: &model.LifeItem{}},
		{Key: "life_inventory", Model: &model.LifeInventory{}},
		{Key: "life_daily_claim", Model: &model.LifeDailyClaim{}},
		{Key: "pet_profiles", Model: &model.PetProfile{}},
		{Key: "pet_friendships", Model: &model.PetFriendship{}},
		{Key: "companion_profiles", Model: &model.CompanionProfile{}},
		{Key: "companion_memories", Model: &model.CompanionMemory{}},
		{Key: "companion_memory_conflicts", Model: &model.CompanionMemoryConflict{}},
		{Key: "companion_chat_logs", Model: &model.CompanionChatLog{}},
		{Key: "companion_relationship_events", Model: &model.CompanionRelationshipEvent{}},
		{Key: "companion_events", Model: &model.CompanionEvent{}},
	}
}
