// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/gift/v1/gift.proto

package giftv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GiftApp_Ping_FullMethodName = "/gift.v1.GiftApp/Ping"
)

// GiftAppClient is the client API for GiftApp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GiftAppClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
}

type giftAppClient struct {
	cc grpc.ClientConnInterface
}

func NewGiftAppClient(cc grpc.ClientConnInterface) GiftAppClient {
	return &giftAppClient{cc}
}

func (c *giftAppClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingReply)
	err := c.cc.Invoke(ctx, GiftApp_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GiftAppServer is the server API for GiftApp service.
// All implementations must embed UnimplementedGiftAppServer
// for forward compatibility.
type GiftAppServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	mustEmbedUnimplementedGiftAppServer()
}

// UnimplementedGiftAppServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGiftAppServer struct{}

func (UnimplementedGiftAppServer) Ping(context.Context, *PingRequest) (*PingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedGiftAppServer) mustEmbedUnimplementedGiftAppServer() {}
func (UnimplementedGiftAppServer) testEmbeddedByValue()                 {}

// UnsafeGiftAppServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GiftAppServer will
// result in compilation errors.
type UnsafeGiftAppServer interface {
	mustEmbedUnimplementedGiftAppServer()
}

func RegisterGiftAppServer(s grpc.ServiceRegistrar, srv GiftAppServer) {
	// If the following call panics, it indicates UnimplementedGiftAppServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GiftApp_ServiceDesc, srv)
}

func _GiftApp_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiftAppServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GiftApp_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiftAppServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GiftApp_ServiceDesc is the grpc.ServiceDesc for GiftApp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GiftApp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gift.v1.GiftApp",
	HandlerType: (*GiftAppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _GiftApp_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/gift/v1/gift.proto",
}
