// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: api/vip/v1/vip.proto

package vipv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VipService_GetVipRecords_FullMethodName          = "/vip.v1.VipService/GetVipRecords"
	VipService_GetUserActiveVipRecord_FullMethodName = "/vip.v1.VipService/GetUserActiveVipRecord"
	VipService_CreateVipOrder_FullMethodName         = "/vip.v1.VipService/CreateVipOrder"
)

// VipServiceClient is the client API for VipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VipServiceClient interface {
	GetVipRecords(ctx context.Context, in *GetVipRecordsRequest, opts ...grpc.CallOption) (*GetVipRecordsReply, error)
	GetUserActiveVipRecord(ctx context.Context, in *GetUserActiveVipRecordRequest, opts ...grpc.CallOption) (*GetUserActiveVipRecordReply, error)
	CreateVipOrder(ctx context.Context, in *CreateVipOrderRequest, opts ...grpc.CallOption) (*CreateVipOrderReply, error)
}

type vipServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVipServiceClient(cc grpc.ClientConnInterface) VipServiceClient {
	return &vipServiceClient{cc}
}

func (c *vipServiceClient) GetVipRecords(ctx context.Context, in *GetVipRecordsRequest, opts ...grpc.CallOption) (*GetVipRecordsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVipRecordsReply)
	err := c.cc.Invoke(ctx, VipService_GetVipRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vipServiceClient) GetUserActiveVipRecord(ctx context.Context, in *GetUserActiveVipRecordRequest, opts ...grpc.CallOption) (*GetUserActiveVipRecordReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserActiveVipRecordReply)
	err := c.cc.Invoke(ctx, VipService_GetUserActiveVipRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vipServiceClient) CreateVipOrder(ctx context.Context, in *CreateVipOrderRequest, opts ...grpc.CallOption) (*CreateVipOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVipOrderReply)
	err := c.cc.Invoke(ctx, VipService_CreateVipOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VipServiceServer is the server API for VipService service.
// All implementations must embed UnimplementedVipServiceServer
// for forward compatibility.
type VipServiceServer interface {
	GetVipRecords(context.Context, *GetVipRecordsRequest) (*GetVipRecordsReply, error)
	GetUserActiveVipRecord(context.Context, *GetUserActiveVipRecordRequest) (*GetUserActiveVipRecordReply, error)
	CreateVipOrder(context.Context, *CreateVipOrderRequest) (*CreateVipOrderReply, error)
	mustEmbedUnimplementedVipServiceServer()
}

// UnimplementedVipServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVipServiceServer struct{}

func (UnimplementedVipServiceServer) GetVipRecords(context.Context, *GetVipRecordsRequest) (*GetVipRecordsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVipRecords not implemented")
}
func (UnimplementedVipServiceServer) GetUserActiveVipRecord(context.Context, *GetUserActiveVipRecordRequest) (*GetUserActiveVipRecordReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserActiveVipRecord not implemented")
}
func (UnimplementedVipServiceServer) CreateVipOrder(context.Context, *CreateVipOrderRequest) (*CreateVipOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVipOrder not implemented")
}
func (UnimplementedVipServiceServer) mustEmbedUnimplementedVipServiceServer() {}
func (UnimplementedVipServiceServer) testEmbeddedByValue()                    {}

// UnsafeVipServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VipServiceServer will
// result in compilation errors.
type UnsafeVipServiceServer interface {
	mustEmbedUnimplementedVipServiceServer()
}

func RegisterVipServiceServer(s grpc.ServiceRegistrar, srv VipServiceServer) {
	// If the following call pancis, it indicates UnimplementedVipServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VipService_ServiceDesc, srv)
}

func _VipService_GetVipRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVipRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VipServiceServer).GetVipRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VipService_GetVipRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VipServiceServer).GetVipRecords(ctx, req.(*GetVipRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VipService_GetUserActiveVipRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserActiveVipRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VipServiceServer).GetUserActiveVipRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VipService_GetUserActiveVipRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VipServiceServer).GetUserActiveVipRecord(ctx, req.(*GetUserActiveVipRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VipService_CreateVipOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVipOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VipServiceServer).CreateVipOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VipService_CreateVipOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VipServiceServer).CreateVipOrder(ctx, req.(*CreateVipOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VipService_ServiceDesc is the grpc.ServiceDesc for VipService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VipService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vip.v1.VipService",
	HandlerType: (*VipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVipRecords",
			Handler:    _VipService_GetVipRecords_Handler,
		},
		{
			MethodName: "GetUserActiveVipRecord",
			Handler:    _VipService_GetUserActiveVipRecord_Handler,
		},
		{
			MethodName: "CreateVipOrder",
			Handler:    _VipService_CreateVipOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/vip/v1/vip.proto",
}
