// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/chat/v1/private_message.proto

package chatv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrivateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    string                 `protobuf:"bytes,3,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	ImagePaths    []string               `protobuf:"bytes,5,rep,name=image_paths,json=imagePaths,proto3" json:"image_paths,omitempty"`
	RetentionDays int32                  `protobuf:"varint,6,opt,name=retention_days,json=retentionDays,proto3" json:"retention_days,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	SenderMoeNo   string                 `protobuf:"bytes,9,opt,name=sender_moe_no,json=senderMoeNo,proto3" json:"sender_moe_no,omitempty"`
	ReceiverMoeNo string                 `protobuf:"bytes,10,opt,name=receiver_moe_no,json=receiverMoeNo,proto3" json:"receiver_moe_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateMessage) Reset() {
	*x = PrivateMessage{}
	mi := &file_api_chat_v1_private_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateMessage) ProtoMessage() {}

func (x *PrivateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_private_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateMessage.ProtoReflect.Descriptor instead.
func (*PrivateMessage) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_private_message_proto_rawDescGZIP(), []int{0}
}

func (x *PrivateMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PrivateMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *PrivateMessage) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *PrivateMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *PrivateMessage) GetImagePaths() []string {
	if x != nil {
		return x.ImagePaths
	}
	return nil
}

func (x *PrivateMessage) GetRetentionDays() int32 {
	if x != nil {
		return x.RetentionDays
	}
	return 0
}

func (x *PrivateMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PrivateMessage) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *PrivateMessage) GetSenderMoeNo() string {
	if x != nil {
		return x.SenderMoeNo
	}
	return ""
}

func (x *PrivateMessage) GetReceiverMoeNo() string {
	if x != nil {
		return x.ReceiverMoeNo
	}
	return ""
}

type SendPrivateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    string                 `protobuf:"bytes,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	ImagePaths    []string               `protobuf:"bytes,4,rep,name=image_paths,json=imagePaths,proto3" json:"image_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPrivateMessageRequest) Reset() {
	*x = SendPrivateMessageRequest{}
	mi := &file_api_chat_v1_private_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPrivateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPrivateMessageRequest) ProtoMessage() {}

func (x *SendPrivateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_private_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPrivateMessageRequest.ProtoReflect.Descriptor instead.
func (*SendPrivateMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_private_message_proto_rawDescGZIP(), []int{1}
}

func (x *SendPrivateMessageRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SendPrivateMessageRequest) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *SendPrivateMessageRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendPrivateMessageRequest) GetImagePaths() []string {
	if x != nil {
		return x.ImagePaths
	}
	return nil
}

type SendPrivateMessageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *PrivateMessage        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPrivateMessageReply) Reset() {
	*x = SendPrivateMessageReply{}
	mi := &file_api_chat_v1_private_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPrivateMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPrivateMessageReply) ProtoMessage() {}

func (x *SendPrivateMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_private_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPrivateMessageReply.ProtoReflect.Descriptor instead.
func (*SendPrivateMessageReply) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_private_message_proto_rawDescGZIP(), []int{2}
}

func (x *SendPrivateMessageReply) GetMessage() *PrivateMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type ListPrivateMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewerId      string                 `protobuf:"bytes,1,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	BeforeId      string                 `protobuf:"bytes,3,opt,name=before_id,json=beforeId,proto3" json:"before_id,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrivateMessagesRequest) Reset() {
	*x = ListPrivateMessagesRequest{}
	mi := &file_api_chat_v1_private_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrivateMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrivateMessagesRequest) ProtoMessage() {}

func (x *ListPrivateMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_private_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrivateMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListPrivateMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_private_message_proto_rawDescGZIP(), []int{3}
}

func (x *ListPrivateMessagesRequest) GetViewerId() string {
	if x != nil {
		return x.ViewerId
	}
	return ""
}

func (x *ListPrivateMessagesRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *ListPrivateMessagesRequest) GetBeforeId() string {
	if x != nil {
		return x.BeforeId
	}
	return ""
}

func (x *ListPrivateMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListPrivateMessagesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*PrivateMessage      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrivateMessagesReply) Reset() {
	*x = ListPrivateMessagesReply{}
	mi := &file_api_chat_v1_private_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrivateMessagesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrivateMessagesReply) ProtoMessage() {}

func (x *ListPrivateMessagesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_private_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrivateMessagesReply.ProtoReflect.Descriptor instead.
func (*ListPrivateMessagesReply) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_private_message_proto_rawDescGZIP(), []int{4}
}

func (x *ListPrivateMessagesReply) GetMessages() []*PrivateMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListPrivateMessagesReply) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type PrivateConversation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PeerId            string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	PeerName          string                 `protobuf:"bytes,2,opt,name=peer_name,json=peerName,proto3" json:"peer_name,omitempty"`
	PeerAvatar        string                 `protobuf:"bytes,3,opt,name=peer_avatar,json=peerAvatar,proto3" json:"peer_avatar,omitempty"`
	PeerMoeNo         string                 `protobuf:"bytes,4,opt,name=peer_moe_no,json=peerMoeNo,proto3" json:"peer_moe_no,omitempty"`
	PeerDisplayUserId string                 `protobuf:"bytes,5,opt,name=peer_display_user_id,json=peerDisplayUserId,proto3" json:"peer_display_user_id,omitempty"`
	LastMessage       *PrivateMessage        `protobuf:"bytes,6,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	UnreadCount       int32                  `protobuf:"varint,7,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PrivateConversation) Reset() {
	*x = PrivateConversation{}
	mi := &file_api_chat_v1_private_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateConversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateConversation) ProtoMessage() {}

func (x *PrivateConversation) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_private_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateConversation.ProtoReflect.Descriptor instead.
func (*PrivateConversation) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_private_message_proto_rawDescGZIP(), []int{5}
}

func (x *PrivateConversation) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PrivateConversation) GetPeerName() string {
	if x != nil {
		return x.PeerName
	}
	return ""
}

func (x *PrivateConversation) GetPeerAvatar() string {
	if x != nil {
		return x.PeerAvatar
	}
	return ""
}

func (x *PrivateConversation) GetPeerMoeNo() string {
	if x != nil {
		return x.PeerMoeNo
	}
	return ""
}

func (x *PrivateConversation) GetPeerDisplayUserId() string {
	if x != nil {
		return x.PeerDisplayUserId
	}
	return ""
}

func (x *PrivateConversation) GetLastMessage() *PrivateMessage {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

func (x *PrivateConversation) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type ListPrivateConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewerId      string                 `protobuf:"bytes,1,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrivateConversationsRequest) Reset() {
	*x = ListPrivateConversationsRequest{}
	mi := &file_api_chat_v1_private_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrivateConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrivateConversationsRequest) ProtoMessage() {}

func (x *ListPrivateConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_private_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrivateConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListPrivateConversationsRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_private_message_proto_rawDescGZIP(), []int{6}
}

func (x *ListPrivateConversationsRequest) GetViewerId() string {
	if x != nil {
		return x.ViewerId
	}
	return ""
}

func (x *ListPrivateConversationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPrivateConversationsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListPrivateConversationsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*PrivateConversation `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	HasMore       bool                   `protobuf:"varint,5,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrivateConversationsReply) Reset() {
	*x = ListPrivateConversationsReply{}
	mi := &file_api_chat_v1_private_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrivateConversationsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrivateConversationsReply) ProtoMessage() {}

func (x *ListPrivateConversationsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_private_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrivateConversationsReply.ProtoReflect.Descriptor instead.
func (*ListPrivateConversationsReply) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_private_message_proto_rawDescGZIP(), []int{7}
}

func (x *ListPrivateConversationsReply) GetConversations() []*PrivateConversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *ListPrivateConversationsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListPrivateConversationsReply) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPrivateConversationsReply) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListPrivateConversationsReply) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_api_chat_v1_private_message_proto protoreflect.FileDescriptor

const file_api_chat_v1_private_message_proto_rawDesc = "" +
	"\n" +
	"!api/chat/v1/private_message.proto\x12\achat.v1\x1a\x1cgoogle/api/annotations.proto\"\xc4\x02\n" +
	"\x0ePrivateMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x03 \x01(\tR\n" +
	"receiverId\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1f\n" +
	"\vimage_paths\x18\x05 \x03(\tR\n" +
	"imagePaths\x12%\n" +
	"\x0eretention_days\x18\x06 \x01(\x05R\rretentionDays\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\tR\texpiresAt\x12\"\n" +
	"\rsender_moe_no\x18\t \x01(\tR\vsenderMoeNo\x12&\n" +
	"\x0freceiver_moe_no\x18\n" +
	" \x01(\tR\rreceiverMoeNo\"\x8e\x01\n" +
	"\x19SendPrivateMessageRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\tR\n" +
	"receiverId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x1f\n" +
	"\vimage_paths\x18\x04 \x03(\tR\n" +
	"imagePaths\"L\n" +
	"\x17SendPrivateMessageReply\x121\n" +
	"\amessage\x18\x01 \x01(\v2\x17.chat.v1.PrivateMessageR\amessage\"\x85\x01\n" +
	"\x1aListPrivateMessagesRequest\x12\x1b\n" +
	"\tviewer_id\x18\x01 \x01(\tR\bviewerId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12\x1b\n" +
	"\tbefore_id\x18\x03 \x01(\tR\bbeforeId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"j\n" +
	"\x18ListPrivateMessagesReply\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.chat.v1.PrivateMessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"\x9c\x02\n" +
	"\x13PrivateConversation\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1b\n" +
	"\tpeer_name\x18\x02 \x01(\tR\bpeerName\x12\x1f\n" +
	"\vpeer_avatar\x18\x03 \x01(\tR\n" +
	"peerAvatar\x12\x1e\n" +
	"\vpeer_moe_no\x18\x04 \x01(\tR\tpeerMoeNo\x12/\n" +
	"\x14peer_display_user_id\x18\x05 \x01(\tR\x11peerDisplayUserId\x12:\n" +
	"\flast_message\x18\x06 \x01(\v2\x17.chat.v1.PrivateMessageR\vlastMessage\x12!\n" +
	"\funread_count\x18\a \x01(\x05R\vunreadCount\"l\n" +
	"\x1fListPrivateConversationsRequest\x12\x1b\n" +
	"\tviewer_id\x18\x01 \x01(\tR\bviewerId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\xc2\x01\n" +
	"\x1dListPrivateConversationsReply\x12B\n" +
	"\rconversations\x18\x01 \x03(\v2\x1c.chat.v1.PrivateConversationR\rconversations\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x19\n" +
	"\bhas_more\x18\x05 \x01(\bR\ahasMore2\xaf\x03\n" +
	"\x15PrivateMessageService\x12|\n" +
	"\x12SendPrivateMessage\x12\".chat.v1.SendPrivateMessageRequest\x1a .chat.v1.SendPrivateMessageReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/private-messages\x12|\n" +
	"\x13ListPrivateMessages\x12#.chat.v1.ListPrivateMessagesRequest\x1a!.chat.v1.ListPrivateMessagesReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/private-messages\x12\x99\x01\n" +
	"\x18ListPrivateConversations\x12(.chat.v1.ListPrivateConversationsRequest\x1a&.chat.v1.ListPrivateConversationsReply\"+\x82\xd3\xe4\x93\x02%\x12#/api/private-messages/conversationsB\x1cZ\x1abackend/api/chat/v1;chatv1b\x06proto3"

var (
	file_api_chat_v1_private_message_proto_rawDescOnce sync.Once
	file_api_chat_v1_private_message_proto_rawDescData []byte
)

func file_api_chat_v1_private_message_proto_rawDescGZIP() []byte {
	file_api_chat_v1_private_message_proto_rawDescOnce.Do(func() {
		file_api_chat_v1_private_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_chat_v1_private_message_proto_rawDesc), len(file_api_chat_v1_private_message_proto_rawDesc)))
	})
	return file_api_chat_v1_private_message_proto_rawDescData
}

var file_api_chat_v1_private_message_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_chat_v1_private_message_proto_goTypes = []any{
	(*PrivateMessage)(nil),                  // 0: chat.v1.PrivateMessage
	(*SendPrivateMessageRequest)(nil),       // 1: chat.v1.SendPrivateMessageRequest
	(*SendPrivateMessageReply)(nil),         // 2: chat.v1.SendPrivateMessageReply
	(*ListPrivateMessagesRequest)(nil),      // 3: chat.v1.ListPrivateMessagesRequest
	(*ListPrivateMessagesReply)(nil),        // 4: chat.v1.ListPrivateMessagesReply
	(*PrivateConversation)(nil),             // 5: chat.v1.PrivateConversation
	(*ListPrivateConversationsRequest)(nil), // 6: chat.v1.ListPrivateConversationsRequest
	(*ListPrivateConversationsReply)(nil),   // 7: chat.v1.ListPrivateConversationsReply
}
var file_api_chat_v1_private_message_proto_depIdxs = []int32{
	0, // 0: chat.v1.SendPrivateMessageReply.message:type_name -> chat.v1.PrivateMessage
	0, // 1: chat.v1.ListPrivateMessagesReply.messages:type_name -> chat.v1.PrivateMessage
	0, // 2: chat.v1.PrivateConversation.last_message:type_name -> chat.v1.PrivateMessage
	5, // 3: chat.v1.ListPrivateConversationsReply.conversations:type_name -> chat.v1.PrivateConversation
	1, // 4: chat.v1.PrivateMessageService.SendPrivateMessage:input_type -> chat.v1.SendPrivateMessageRequest
	3, // 5: chat.v1.PrivateMessageService.ListPrivateMessages:input_type -> chat.v1.ListPrivateMessagesRequest
	6, // 6: chat.v1.PrivateMessageService.ListPrivateConversations:input_type -> chat.v1.ListPrivateConversationsRequest
	2, // 7: chat.v1.PrivateMessageService.SendPrivateMessage:output_type -> chat.v1.SendPrivateMessageReply
	4, // 8: chat.v1.PrivateMessageService.ListPrivateMessages:output_type -> chat.v1.ListPrivateMessagesReply
	7, // 9: chat.v1.PrivateMessageService.ListPrivateConversations:output_type -> chat.v1.ListPrivateConversationsReply
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_chat_v1_private_message_proto_init() }
func file_api_chat_v1_private_message_proto_init() {
	if File_api_chat_v1_private_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_chat_v1_private_message_proto_rawDesc), len(file_api_chat_v1_private_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_chat_v1_private_message_proto_goTypes,
		DependencyIndexes: file_api_chat_v1_private_message_proto_depIdxs,
		MessageInfos:      file_api_chat_v1_private_message_proto_msgTypes,
	}.Build()
	File_api_chat_v1_private_message_proto = out.File
	file_api_chat_v1_private_message_proto_goTypes = nil
	file_api_chat_v1_private_message_proto_depIdxs = nil
}
