// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/llm/v1/llm_messages.proto

package llmv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAiUserConfigReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAiUserConfigReq) Reset() {
	*x = GetAiUserConfigReq{}
	mi := &file_api_llm_v1_llm_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAiUserConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAiUserConfigReq) ProtoMessage() {}

func (x *GetAiUserConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_llm_v1_llm_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAiUserConfigReq.ProtoReflect.Descriptor instead.
func (*GetAiUserConfigReq) Descriptor() ([]byte, []int) {
	return file_api_llm_v1_llm_messages_proto_rawDescGZIP(), []int{0}
}

func (x *GetAiUserConfigReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAiUserConfigResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserPersona     string                 `protobuf:"bytes,1,opt,name=user_persona,json=userPersona,proto3" json:"user_persona,omitempty"`
	PreferencesJson string                 `protobuf:"bytes,2,opt,name=preferences_json,json=preferencesJson,proto3" json:"preferences_json,omitempty"`
	// 已明确开启账号同步的 Provider API Key；服务端只保存密文。
	ProviderApiKeysJson string `protobuf:"bytes,3,opt,name=provider_api_keys_json,json=providerApiKeysJson,proto3" json:"provider_api_keys_json,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetAiUserConfigResp) Reset() {
	*x = GetAiUserConfigResp{}
	mi := &file_api_llm_v1_llm_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAiUserConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAiUserConfigResp) ProtoMessage() {}

func (x *GetAiUserConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_llm_v1_llm_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAiUserConfigResp.ProtoReflect.Descriptor instead.
func (*GetAiUserConfigResp) Descriptor() ([]byte, []int) {
	return file_api_llm_v1_llm_messages_proto_rawDescGZIP(), []int{1}
}

func (x *GetAiUserConfigResp) GetUserPersona() string {
	if x != nil {
		return x.UserPersona
	}
	return ""
}

func (x *GetAiUserConfigResp) GetPreferencesJson() string {
	if x != nil {
		return x.PreferencesJson
	}
	return ""
}

func (x *GetAiUserConfigResp) GetProviderApiKeysJson() string {
	if x != nil {
		return x.ProviderApiKeysJson
	}
	return ""
}

type UpsertAiUserConfigReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserPersona     string                 `protobuf:"bytes,2,opt,name=user_persona,json=userPersona,proto3" json:"user_persona,omitempty"`
	HasUserPersona  bool                   `protobuf:"varint,3,opt,name=has_user_persona,json=hasUserPersona,proto3" json:"has_user_persona,omitempty"`
	PreferencesJson string                 `protobuf:"bytes,4,opt,name=preferences_json,json=preferencesJson,proto3" json:"preferences_json,omitempty"`
	// 单个 Provider 密钥的增量写入；key 为空表示删除云端密钥。
	ProviderApiKeyProfileId string `protobuf:"bytes,5,opt,name=provider_api_key_profile_id,json=providerApiKeyProfileId,proto3" json:"provider_api_key_profile_id,omitempty"`
	ProviderApiKey          string `protobuf:"bytes,6,opt,name=provider_api_key,json=providerApiKey,proto3" json:"provider_api_key,omitempty"`
	HasProviderApiKey       bool   `protobuf:"varint,7,opt,name=has_provider_api_key,json=hasProviderApiKey,proto3" json:"has_provider_api_key,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UpsertAiUserConfigReq) Reset() {
	*x = UpsertAiUserConfigReq{}
	mi := &file_api_llm_v1_llm_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertAiUserConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAiUserConfigReq) ProtoMessage() {}

func (x *UpsertAiUserConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_llm_v1_llm_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAiUserConfigReq.ProtoReflect.Descriptor instead.
func (*UpsertAiUserConfigReq) Descriptor() ([]byte, []int) {
	return file_api_llm_v1_llm_messages_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertAiUserConfigReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpsertAiUserConfigReq) GetUserPersona() string {
	if x != nil {
		return x.UserPersona
	}
	return ""
}

func (x *UpsertAiUserConfigReq) GetHasUserPersona() bool {
	if x != nil {
		return x.HasUserPersona
	}
	return false
}

func (x *UpsertAiUserConfigReq) GetPreferencesJson() string {
	if x != nil {
		return x.PreferencesJson
	}
	return ""
}

func (x *UpsertAiUserConfigReq) GetProviderApiKeyProfileId() string {
	if x != nil {
		return x.ProviderApiKeyProfileId
	}
	return ""
}

func (x *UpsertAiUserConfigReq) GetProviderApiKey() string {
	if x != nil {
		return x.ProviderApiKey
	}
	return ""
}

func (x *UpsertAiUserConfigReq) GetHasProviderApiKey() bool {
	if x != nil {
		return x.HasProviderApiKey
	}
	return false
}

type UpsertAiUserConfigResp struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserPersona         string                 `protobuf:"bytes,1,opt,name=user_persona,json=userPersona,proto3" json:"user_persona,omitempty"`
	PreferencesJson     string                 `protobuf:"bytes,2,opt,name=preferences_json,json=preferencesJson,proto3" json:"preferences_json,omitempty"`
	ProviderApiKeysJson string                 `protobuf:"bytes,3,opt,name=provider_api_keys_json,json=providerApiKeysJson,proto3" json:"provider_api_keys_json,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpsertAiUserConfigResp) Reset() {
	*x = UpsertAiUserConfigResp{}
	mi := &file_api_llm_v1_llm_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertAiUserConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAiUserConfigResp) ProtoMessage() {}

func (x *UpsertAiUserConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_llm_v1_llm_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAiUserConfigResp.ProtoReflect.Descriptor instead.
func (*UpsertAiUserConfigResp) Descriptor() ([]byte, []int) {
	return file_api_llm_v1_llm_messages_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertAiUserConfigResp) GetUserPersona() string {
	if x != nil {
		return x.UserPersona
	}
	return ""
}

func (x *UpsertAiUserConfigResp) GetPreferencesJson() string {
	if x != nil {
		return x.PreferencesJson
	}
	return ""
}

func (x *UpsertAiUserConfigResp) GetProviderApiKeysJson() string {
	if x != nil {
		return x.ProviderApiKeysJson
	}
	return ""
}

type ListLlmModelsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLlmModelsReq) Reset() {
	*x = ListLlmModelsReq{}
	mi := &file_api_llm_v1_llm_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLlmModelsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLlmModelsReq) ProtoMessage() {}

func (x *ListLlmModelsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_llm_v1_llm_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLlmModelsReq.ProtoReflect.Descriptor instead.
func (*ListLlmModelsReq) Descriptor() ([]byte, []int) {
	return file_api_llm_v1_llm_messages_proto_rawDescGZIP(), []int{4}
}

type ListLlmModelsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []string               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLlmModelsResp) Reset() {
	*x = ListLlmModelsResp{}
	mi := &file_api_llm_v1_llm_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLlmModelsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLlmModelsResp) ProtoMessage() {}

func (x *ListLlmModelsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_llm_v1_llm_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLlmModelsResp.ProtoReflect.Descriptor instead.
func (*ListLlmModelsResp) Descriptor() ([]byte, []int) {
	return file_api_llm_v1_llm_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ListLlmModelsResp) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

type GetLlmModelPromptReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLlmModelPromptReq) Reset() {
	*x = GetLlmModelPromptReq{}
	mi := &file_api_llm_v1_llm_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLlmModelPromptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLlmModelPromptReq) ProtoMessage() {}

func (x *GetLlmModelPromptReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_llm_v1_llm_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLlmModelPromptReq.ProtoReflect.Descriptor instead.
func (*GetLlmModelPromptReq) Descriptor() ([]byte, []int) {
	return file_api_llm_v1_llm_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetLlmModelPromptReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type GetLlmModelPromptResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemPrompt  string                 `protobuf:"bytes,1,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLlmModelPromptResp) Reset() {
	*x = GetLlmModelPromptResp{}
	mi := &file_api_llm_v1_llm_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLlmModelPromptResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLlmModelPromptResp) ProtoMessage() {}

func (x *GetLlmModelPromptResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_llm_v1_llm_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLlmModelPromptResp.ProtoReflect.Descriptor instead.
func (*GetLlmModelPromptResp) Descriptor() ([]byte, []int) {
	return file_api_llm_v1_llm_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GetLlmModelPromptResp) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

var File_api_llm_v1_llm_messages_proto protoreflect.FileDescriptor

const file_api_llm_v1_llm_messages_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/llm/v1/llm_messages.proto\x12\x06llm.v1\x1a\x1cgoogle/api/annotations.proto\"-\n" +
	"\x12GetAiUserConfigReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x98\x01\n" +
	"\x13GetAiUserConfigResp\x12!\n" +
	"\fuser_persona\x18\x01 \x01(\tR\vuserPersona\x12)\n" +
	"\x10preferences_json\x18\x02 \x01(\tR\x0fpreferencesJson\x123\n" +
	"\x16provider_api_keys_json\x18\x03 \x01(\tR\x13providerApiKeysJson\"\xc1\x02\n" +
	"\x15UpsertAiUserConfigReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fuser_persona\x18\x02 \x01(\tR\vuserPersona\x12(\n" +
	"\x10has_user_persona\x18\x03 \x01(\bR\x0ehasUserPersona\x12)\n" +
	"\x10preferences_json\x18\x04 \x01(\tR\x0fpreferencesJson\x12<\n" +
	"\x1bprovider_api_key_profile_id\x18\x05 \x01(\tR\x17providerApiKeyProfileId\x12(\n" +
	"\x10provider_api_key\x18\x06 \x01(\tR\x0eproviderApiKey\x12/\n" +
	"\x14has_provider_api_key\x18\a \x01(\bR\x11hasProviderApiKey\"\x9b\x01\n" +
	"\x16UpsertAiUserConfigResp\x12!\n" +
	"\fuser_persona\x18\x01 \x01(\tR\vuserPersona\x12)\n" +
	"\x10preferences_json\x18\x02 \x01(\tR\x0fpreferencesJson\x123\n" +
	"\x16provider_api_keys_json\x18\x03 \x01(\tR\x13providerApiKeysJson\"\x12\n" +
	"\x10ListLlmModelsReq\"+\n" +
	"\x11ListLlmModelsResp\x12\x16\n" +
	"\x06models\x18\x01 \x03(\tR\x06models\",\n" +
	"\x14GetLlmModelPromptReq\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\"<\n" +
	"\x15GetLlmModelPromptResp\x12#\n" +
	"\rsystem_prompt\x18\x01 \x01(\tR\fsystemPrompt2\xad\x03\n" +
	"\aLlmChat\x12b\n" +
	"\x0fGetAiUserConfig\x12\x1a.llm.v1.GetAiUserConfigReq\x1a\x1b.llm.v1.GetAiUserConfigResp\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/ai/config\x12n\n" +
	"\x12UpsertAiUserConfig\x12\x1d.llm.v1.UpsertAiUserConfigReq\x1a\x1e.llm.v1.UpsertAiUserConfigResp\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/api/ai/config\x12]\n" +
	"\rListLlmModels\x12\x18.llm.v1.ListLlmModelsReq\x1a\x19.llm.v1.ListLlmModelsResp\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/llm/models\x12o\n" +
	"\x11GetLlmModelPrompt\x12\x1c.llm.v1.GetLlmModelPromptReq\x1a\x1d.llm.v1.GetLlmModelPromptResp\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/llm/model-promptB\x1aZ\x18backend/api/llm/v1;llmv1b\x06proto3"

var (
	file_api_llm_v1_llm_messages_proto_rawDescOnce sync.Once
	file_api_llm_v1_llm_messages_proto_rawDescData []byte
)

func file_api_llm_v1_llm_messages_proto_rawDescGZIP() []byte {
	file_api_llm_v1_llm_messages_proto_rawDescOnce.Do(func() {
		file_api_llm_v1_llm_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_llm_v1_llm_messages_proto_rawDesc), len(file_api_llm_v1_llm_messages_proto_rawDesc)))
	})
	return file_api_llm_v1_llm_messages_proto_rawDescData
}

var file_api_llm_v1_llm_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_llm_v1_llm_messages_proto_goTypes = []any{
	(*GetAiUserConfigReq)(nil),     // 0: llm.v1.GetAiUserConfigReq
	(*GetAiUserConfigResp)(nil),    // 1: llm.v1.GetAiUserConfigResp
	(*UpsertAiUserConfigReq)(nil),  // 2: llm.v1.UpsertAiUserConfigReq
	(*UpsertAiUserConfigResp)(nil), // 3: llm.v1.UpsertAiUserConfigResp
	(*ListLlmModelsReq)(nil),       // 4: llm.v1.ListLlmModelsReq
	(*ListLlmModelsResp)(nil),      // 5: llm.v1.ListLlmModelsResp
	(*GetLlmModelPromptReq)(nil),   // 6: llm.v1.GetLlmModelPromptReq
	(*GetLlmModelPromptResp)(nil),  // 7: llm.v1.GetLlmModelPromptResp
}
var file_api_llm_v1_llm_messages_proto_depIdxs = []int32{
	0, // 0: llm.v1.LlmChat.GetAiUserConfig:input_type -> llm.v1.GetAiUserConfigReq
	2, // 1: llm.v1.LlmChat.UpsertAiUserConfig:input_type -> llm.v1.UpsertAiUserConfigReq
	4, // 2: llm.v1.LlmChat.ListLlmModels:input_type -> llm.v1.ListLlmModelsReq
	6, // 3: llm.v1.LlmChat.GetLlmModelPrompt:input_type -> llm.v1.GetLlmModelPromptReq
	1, // 4: llm.v1.LlmChat.GetAiUserConfig:output_type -> llm.v1.GetAiUserConfigResp
	3, // 5: llm.v1.LlmChat.UpsertAiUserConfig:output_type -> llm.v1.UpsertAiUserConfigResp
	5, // 6: llm.v1.LlmChat.ListLlmModels:output_type -> llm.v1.ListLlmModelsResp
	7, // 7: llm.v1.LlmChat.GetLlmModelPrompt:output_type -> llm.v1.GetLlmModelPromptResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_llm_v1_llm_messages_proto_init() }
func file_api_llm_v1_llm_messages_proto_init() {
	if File_api_llm_v1_llm_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_llm_v1_llm_messages_proto_rawDesc), len(file_api_llm_v1_llm_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_llm_v1_llm_messages_proto_goTypes,
		DependencyIndexes: file_api_llm_v1_llm_messages_proto_depIdxs,
		MessageInfos:      file_api_llm_v1_llm_messages_proto_msgTypes,
	}.Build()
	File_api_llm_v1_llm_messages_proto = out.File
	file_api_llm_v1_llm_messages_proto_goTypes = nil
	file_api_llm_v1_llm_messages_proto_depIdxs = nil
}
