// SSOT stub (documentation-only). Mirrors super.proto LLM chat RPCs.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/llm/v1/llm_chat.proto

package llmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostChatCompletionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostChatCompletionReq) Reset() {
	*x = PostChatCompletionReq{}
	mi := &file_api_llm_v1_llm_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostChatCompletionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostChatCompletionReq) ProtoMessage() {}

func (x *PostChatCompletionReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_llm_v1_llm_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostChatCompletionReq.ProtoReflect.Descriptor instead.
func (*PostChatCompletionReq) Descriptor() ([]byte, []int) {
	return file_api_llm_v1_llm_chat_proto_rawDescGZIP(), []int{0}
}

type PostChatCompletionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostChatCompletionResp) Reset() {
	*x = PostChatCompletionResp{}
	mi := &file_api_llm_v1_llm_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostChatCompletionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostChatCompletionResp) ProtoMessage() {}

func (x *PostChatCompletionResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_llm_v1_llm_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostChatCompletionResp.ProtoReflect.Descriptor instead.
func (*PostChatCompletionResp) Descriptor() ([]byte, []int) {
	return file_api_llm_v1_llm_chat_proto_rawDescGZIP(), []int{1}
}

var File_api_llm_v1_llm_chat_proto protoreflect.FileDescriptor

const file_api_llm_v1_llm_chat_proto_rawDesc = "" +
	"\n" +
	"\x19api/llm/v1/llm_chat.proto\x12\x06llm.v1\"\x17\n" +
	"\x15PostChatCompletionReq\"\x18\n" +
	"\x16PostChatCompletionResp2^\n" +
	"\aLlmChat\x12S\n" +
	"\x12PostChatCompletion\x12\x1d.llm.v1.PostChatCompletionReq\x1a\x1e.llm.v1.PostChatCompletionRespB\x1aZ\x18backend/api/llm/v1;llmv1b\x06proto3"

var (
	file_api_llm_v1_llm_chat_proto_rawDescOnce sync.Once
	file_api_llm_v1_llm_chat_proto_rawDescData []byte
)

func file_api_llm_v1_llm_chat_proto_rawDescGZIP() []byte {
	file_api_llm_v1_llm_chat_proto_rawDescOnce.Do(func() {
		file_api_llm_v1_llm_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_llm_v1_llm_chat_proto_rawDesc), len(file_api_llm_v1_llm_chat_proto_rawDesc)))
	})
	return file_api_llm_v1_llm_chat_proto_rawDescData
}

var file_api_llm_v1_llm_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_llm_v1_llm_chat_proto_goTypes = []any{
	(*PostChatCompletionReq)(nil),  // 0: llm.v1.PostChatCompletionReq
	(*PostChatCompletionResp)(nil), // 1: llm.v1.PostChatCompletionResp
}
var file_api_llm_v1_llm_chat_proto_depIdxs = []int32{
	0, // 0: llm.v1.LlmChat.PostChatCompletion:input_type -> llm.v1.PostChatCompletionReq
	1, // 1: llm.v1.LlmChat.PostChatCompletion:output_type -> llm.v1.PostChatCompletionResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_llm_v1_llm_chat_proto_init() }
func file_api_llm_v1_llm_chat_proto_init() {
	if File_api_llm_v1_llm_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_llm_v1_llm_chat_proto_rawDesc), len(file_api_llm_v1_llm_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_llm_v1_llm_chat_proto_goTypes,
		DependencyIndexes: file_api_llm_v1_llm_chat_proto_depIdxs,
		MessageInfos:      file_api_llm_v1_llm_chat_proto_msgTypes,
	}.Build()
	File_api_llm_v1_llm_chat_proto = out.File
	file_api_llm_v1_llm_chat_proto_goTypes = nil
	file_api_llm_v1_llm_chat_proto_depIdxs = nil
}
