// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: api/checkin/v1/checkin.proto

package checkinv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserLevelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Experience    int32                  `protobuf:"varint,2,opt,name=experience,proto3" json:"experience,omitempty"`
	TotalExp      int32                  `protobuf:"varint,3,opt,name=total_exp,json=totalExp,proto3" json:"total_exp,omitempty"`
	NextLevelExp  int32                  `protobuf:"varint,4,opt,name=next_level_exp,json=nextLevelExp,proto3" json:"next_level_exp,omitempty"`
	LevelTitle    string                 `protobuf:"bytes,5,opt,name=level_title,json=levelTitle,proto3" json:"level_title,omitempty"`
	BadgeUrl      string                 `protobuf:"bytes,6,opt,name=badge_url,json=badgeUrl,proto3" json:"badge_url,omitempty"`
	Progress      float64                `protobuf:"fixed64,7,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLevelInfo) Reset() {
	*x = UserLevelInfo{}
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLevelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLevelInfo) ProtoMessage() {}

func (x *UserLevelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLevelInfo.ProtoReflect.Descriptor instead.
func (*UserLevelInfo) Descriptor() ([]byte, []int) {
	return file_api_checkin_v1_checkin_proto_rawDescGZIP(), []int{0}
}

func (x *UserLevelInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserLevelInfo) GetExperience() int32 {
	if x != nil {
		return x.Experience
	}
	return 0
}

func (x *UserLevelInfo) GetTotalExp() int32 {
	if x != nil {
		return x.TotalExp
	}
	return 0
}

func (x *UserLevelInfo) GetNextLevelExp() int32 {
	if x != nil {
		return x.NextLevelExp
	}
	return 0
}

func (x *UserLevelInfo) GetLevelTitle() string {
	if x != nil {
		return x.LevelTitle
	}
	return ""
}

func (x *UserLevelInfo) GetBadgeUrl() string {
	if x != nil {
		return x.BadgeUrl
	}
	return ""
}

func (x *UserLevelInfo) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type CheckInStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HasCheckedToday bool                   `protobuf:"varint,1,opt,name=has_checked_today,json=hasCheckedToday,proto3" json:"has_checked_today,omitempty"`
	ConsecutiveDays int32                  `protobuf:"varint,2,opt,name=consecutive_days,json=consecutiveDays,proto3" json:"consecutive_days,omitempty"`
	TodayReward     int32                  `protobuf:"varint,3,opt,name=today_reward,json=todayReward,proto3" json:"today_reward,omitempty"`
	NextDayReward   int32                  `protobuf:"varint,4,opt,name=next_day_reward,json=nextDayReward,proto3" json:"next_day_reward,omitempty"`
	CanCheckIn      bool                   `protobuf:"varint,5,opt,name=can_check_in,json=canCheckIn,proto3" json:"can_check_in,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckInStatus) Reset() {
	*x = CheckInStatus{}
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInStatus) ProtoMessage() {}

func (x *CheckInStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInStatus.ProtoReflect.Descriptor instead.
func (*CheckInStatus) Descriptor() ([]byte, []int) {
	return file_api_checkin_v1_checkin_proto_rawDescGZIP(), []int{1}
}

func (x *CheckInStatus) GetHasCheckedToday() bool {
	if x != nil {
		return x.HasCheckedToday
	}
	return false
}

func (x *CheckInStatus) GetConsecutiveDays() int32 {
	if x != nil {
		return x.ConsecutiveDays
	}
	return 0
}

func (x *CheckInStatus) GetTodayReward() int32 {
	if x != nil {
		return x.TodayReward
	}
	return 0
}

func (x *CheckInStatus) GetNextDayReward() int32 {
	if x != nil {
		return x.NextDayReward
	}
	return 0
}

func (x *CheckInStatus) GetCanCheckIn() bool {
	if x != nil {
		return x.CanCheckIn
	}
	return false
}

type CheckInRecord struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CheckInDate       string                 `protobuf:"bytes,1,opt,name=check_in_date,json=checkInDate,proto3" json:"check_in_date,omitempty"`
	ConsecutiveDays   int32                  `protobuf:"varint,2,opt,name=consecutive_days,json=consecutiveDays,proto3" json:"consecutive_days,omitempty"`
	ExpReward         int32                  `protobuf:"varint,3,opt,name=exp_reward,json=expReward,proto3" json:"exp_reward,omitempty"`
	IsSpecialReward   bool                   `protobuf:"varint,4,opt,name=is_special_reward,json=isSpecialReward,proto3" json:"is_special_reward,omitempty"`
	SpecialRewardDesc string                 `protobuf:"bytes,5,opt,name=special_reward_desc,json=specialRewardDesc,proto3" json:"special_reward_desc,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CheckInRecord) Reset() {
	*x = CheckInRecord{}
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRecord) ProtoMessage() {}

func (x *CheckInRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRecord.ProtoReflect.Descriptor instead.
func (*CheckInRecord) Descriptor() ([]byte, []int) {
	return file_api_checkin_v1_checkin_proto_rawDescGZIP(), []int{2}
}

func (x *CheckInRecord) GetCheckInDate() string {
	if x != nil {
		return x.CheckInDate
	}
	return ""
}

func (x *CheckInRecord) GetConsecutiveDays() int32 {
	if x != nil {
		return x.ConsecutiveDays
	}
	return 0
}

func (x *CheckInRecord) GetExpReward() int32 {
	if x != nil {
		return x.ExpReward
	}
	return 0
}

func (x *CheckInRecord) GetIsSpecialReward() bool {
	if x != nil {
		return x.IsSpecialReward
	}
	return false
}

func (x *CheckInRecord) GetSpecialRewardDesc() string {
	if x != nil {
		return x.SpecialRewardDesc
	}
	return ""
}

type ExpLogRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpChange     int32                  `protobuf:"varint,2,opt,name=exp_change,json=expChange,proto3" json:"exp_change,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpLogRecord) Reset() {
	*x = ExpLogRecord{}
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpLogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpLogRecord) ProtoMessage() {}

func (x *ExpLogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpLogRecord.ProtoReflect.Descriptor instead.
func (*ExpLogRecord) Descriptor() ([]byte, []int) {
	return file_api_checkin_v1_checkin_proto_rawDescGZIP(), []int{3}
}

func (x *ExpLogRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExpLogRecord) GetExpChange() int32 {
	if x != nil {
		return x.ExpChange
	}
	return 0
}

func (x *ExpLogRecord) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ExpLogRecord) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExpLogRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AchievementUnlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BadgeId       string                 `protobuf:"bytes,1,opt,name=badge_id,json=badgeId,proto3" json:"badge_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ExpGranted    int32                  `protobuf:"varint,3,opt,name=exp_granted,json=expGranted,proto3" json:"exp_granted,omitempty"`
	LevelUp       bool                   `protobuf:"varint,4,opt,name=level_up,json=levelUp,proto3" json:"level_up,omitempty"`
	NewLevel      int32                  `protobuf:"varint,5,opt,name=new_level,json=newLevel,proto3" json:"new_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AchievementUnlock) Reset() {
	*x = AchievementUnlock{}
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AchievementUnlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AchievementUnlock) ProtoMessage() {}

func (x *AchievementUnlock) ProtoReflect() protoreflect.Message {
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AchievementUnlock.ProtoReflect.Descriptor instead.
func (*AchievementUnlock) Descriptor() ([]byte, []int) {
	return file_api_checkin_v1_checkin_proto_rawDescGZIP(), []int{4}
}

func (x *AchievementUnlock) GetBadgeId() string {
	if x != nil {
		return x.BadgeId
	}
	return ""
}

func (x *AchievementUnlock) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AchievementUnlock) GetExpGranted() int32 {
	if x != nil {
		return x.ExpGranted
	}
	return 0
}

func (x *AchievementUnlock) GetLevelUp() bool {
	if x != nil {
		return x.LevelUp
	}
	return false
}

func (x *AchievementUnlock) GetNewLevel() int32 {
	if x != nil {
		return x.NewLevel
	}
	return 0
}

type CheckInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInRequest) Reset() {
	*x = CheckInRequest{}
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRequest) ProtoMessage() {}

func (x *CheckInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRequest.ProtoReflect.Descriptor instead.
func (*CheckInRequest) Descriptor() ([]byte, []int) {
	return file_api_checkin_v1_checkin_proto_rawDescGZIP(), []int{5}
}

func (x *CheckInRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CheckInReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExpGained       int32                  `protobuf:"varint,1,opt,name=exp_gained,json=expGained,proto3" json:"exp_gained,omitempty"`
	NewLevel        int32                  `protobuf:"varint,2,opt,name=new_level,json=newLevel,proto3" json:"new_level,omitempty"`
	ConsecutiveDays int32                  `protobuf:"varint,3,opt,name=consecutive_days,json=consecutiveDays,proto3" json:"consecutive_days,omitempty"`
	LevelUp         bool                   `protobuf:"varint,4,opt,name=level_up,json=levelUp,proto3" json:"level_up,omitempty"`
	SpecialReward   string                 `protobuf:"bytes,5,opt,name=special_reward,json=specialReward,proto3" json:"special_reward,omitempty"`
	NewAchievements []*AchievementUnlock   `protobuf:"bytes,6,rep,name=new_achievements,json=newAchievements,proto3" json:"new_achievements,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckInReply) Reset() {
	*x = CheckInReply{}
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInReply) ProtoMessage() {}

func (x *CheckInReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInReply.ProtoReflect.Descriptor instead.
func (*CheckInReply) Descriptor() ([]byte, []int) {
	return file_api_checkin_v1_checkin_proto_rawDescGZIP(), []int{6}
}

func (x *CheckInReply) GetExpGained() int32 {
	if x != nil {
		return x.ExpGained
	}
	return 0
}

func (x *CheckInReply) GetNewLevel() int32 {
	if x != nil {
		return x.NewLevel
	}
	return 0
}

func (x *CheckInReply) GetConsecutiveDays() int32 {
	if x != nil {
		return x.ConsecutiveDays
	}
	return 0
}

func (x *CheckInReply) GetLevelUp() bool {
	if x != nil {
		return x.LevelUp
	}
	return false
}

func (x *CheckInReply) GetSpecialReward() string {
	if x != nil {
		return x.SpecialReward
	}
	return ""
}

func (x *CheckInReply) GetNewAchievements() []*AchievementUnlock {
	if x != nil {
		return x.NewAchievements
	}
	return nil
}

type GetUserLevelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLevelRequest) Reset() {
	*x = GetUserLevelRequest{}
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLevelRequest) ProtoMessage() {}

func (x *GetUserLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLevelRequest.ProtoReflect.Descriptor instead.
func (*GetUserLevelRequest) Descriptor() ([]byte, []int) {
	return file_api_checkin_v1_checkin_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserLevelRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserLevelReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LevelInfo     *UserLevelInfo         `protobuf:"bytes,1,opt,name=level_info,json=levelInfo,proto3" json:"level_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLevelReply) Reset() {
	*x = GetUserLevelReply{}
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLevelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLevelReply) ProtoMessage() {}

func (x *GetUserLevelReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLevelReply.ProtoReflect.Descriptor instead.
func (*GetUserLevelReply) Descriptor() ([]byte, []int) {
	return file_api_checkin_v1_checkin_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserLevelReply) GetLevelInfo() *UserLevelInfo {
	if x != nil {
		return x.LevelInfo
	}
	return nil
}

type GetCheckInStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckInStatusRequest) Reset() {
	*x = GetCheckInStatusRequest{}
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckInStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckInStatusRequest) ProtoMessage() {}

func (x *GetCheckInStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckInStatusRequest.ProtoReflect.Descriptor instead.
func (*GetCheckInStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_checkin_v1_checkin_proto_rawDescGZIP(), []int{9}
}

func (x *GetCheckInStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetCheckInStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *CheckInStatus         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckInStatusReply) Reset() {
	*x = GetCheckInStatusReply{}
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckInStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckInStatusReply) ProtoMessage() {}

func (x *GetCheckInStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckInStatusReply.ProtoReflect.Descriptor instead.
func (*GetCheckInStatusReply) Descriptor() ([]byte, []int) {
	return file_api_checkin_v1_checkin_proto_rawDescGZIP(), []int{10}
}

func (x *GetCheckInStatusReply) GetStatus() *CheckInStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetCheckInHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckInHistoryRequest) Reset() {
	*x = GetCheckInHistoryRequest{}
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckInHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckInHistoryRequest) ProtoMessage() {}

func (x *GetCheckInHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckInHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetCheckInHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_checkin_v1_checkin_proto_rawDescGZIP(), []int{11}
}

func (x *GetCheckInHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetCheckInHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCheckInHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetCheckInHistoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*CheckInRecord       `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckInHistoryReply) Reset() {
	*x = GetCheckInHistoryReply{}
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckInHistoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckInHistoryReply) ProtoMessage() {}

func (x *GetCheckInHistoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckInHistoryReply.ProtoReflect.Descriptor instead.
func (*GetCheckInHistoryReply) Descriptor() ([]byte, []int) {
	return file_api_checkin_v1_checkin_proto_rawDescGZIP(), []int{12}
}

func (x *GetCheckInHistoryReply) GetRecords() []*CheckInRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *GetCheckInHistoryReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetExpLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpLogsRequest) Reset() {
	*x = GetExpLogsRequest{}
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpLogsRequest) ProtoMessage() {}

func (x *GetExpLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpLogsRequest.ProtoReflect.Descriptor instead.
func (*GetExpLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_checkin_v1_checkin_proto_rawDescGZIP(), []int{13}
}

func (x *GetExpLogsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetExpLogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetExpLogsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetExpLogsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*ExpLogRecord        `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpLogsReply) Reset() {
	*x = GetExpLogsReply{}
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpLogsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpLogsReply) ProtoMessage() {}

func (x *GetExpLogsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_checkin_v1_checkin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpLogsReply.ProtoReflect.Descriptor instead.
func (*GetExpLogsReply) Descriptor() ([]byte, []int) {
	return file_api_checkin_v1_checkin_proto_rawDescGZIP(), []int{14}
}

func (x *GetExpLogsReply) GetLogs() []*ExpLogRecord {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *GetExpLogsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_api_checkin_v1_checkin_proto protoreflect.FileDescriptor

const file_api_checkin_v1_checkin_proto_rawDesc = "" +
	"\n" +
	"\x1capi/checkin/v1/checkin.proto\x12\n" +
	"checkin.v1\"\xe2\x01\n" +
	"\rUserLevelInfo\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12\x1e\n" +
	"\n" +
	"experience\x18\x02 \x01(\x05R\n" +
	"experience\x12\x1b\n" +
	"\ttotal_exp\x18\x03 \x01(\x05R\btotalExp\x12$\n" +
	"\x0enext_level_exp\x18\x04 \x01(\x05R\fnextLevelExp\x12\x1f\n" +
	"\vlevel_title\x18\x05 \x01(\tR\n" +
	"levelTitle\x12\x1b\n" +
	"\tbadge_url\x18\x06 \x01(\tR\bbadgeUrl\x12\x1a\n" +
	"\bprogress\x18\a \x01(\x01R\bprogress\"\xd3\x01\n" +
	"\rCheckInStatus\x12*\n" +
	"\x11has_checked_today\x18\x01 \x01(\bR\x0fhasCheckedToday\x12)\n" +
	"\x10consecutive_days\x18\x02 \x01(\x05R\x0fconsecutiveDays\x12!\n" +
	"\ftoday_reward\x18\x03 \x01(\x05R\vtodayReward\x12&\n" +
	"\x0fnext_day_reward\x18\x04 \x01(\x05R\rnextDayReward\x12 \n" +
	"\fcan_check_in\x18\x05 \x01(\bR\n" +
	"canCheckIn\"\xd9\x01\n" +
	"\rCheckInRecord\x12\"\n" +
	"\rcheck_in_date\x18\x01 \x01(\tR\vcheckInDate\x12)\n" +
	"\x10consecutive_days\x18\x02 \x01(\x05R\x0fconsecutiveDays\x12\x1d\n" +
	"\n" +
	"exp_reward\x18\x03 \x01(\x05R\texpReward\x12*\n" +
	"\x11is_special_reward\x18\x04 \x01(\bR\x0fisSpecialReward\x12.\n" +
	"\x13special_reward_desc\x18\x05 \x01(\tR\x11specialRewardDesc\"\x96\x01\n" +
	"\fExpLogRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"exp_change\x18\x02 \x01(\x05R\texpChange\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\x9b\x01\n" +
	"\x11AchievementUnlock\x12\x19\n" +
	"\bbadge_id\x18\x01 \x01(\tR\abadgeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vexp_granted\x18\x03 \x01(\x05R\n" +
	"expGranted\x12\x19\n" +
	"\blevel_up\x18\x04 \x01(\bR\alevelUp\x12\x1b\n" +
	"\tnew_level\x18\x05 \x01(\x05R\bnewLevel\")\n" +
	"\x0eCheckInRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x81\x02\n" +
	"\fCheckInReply\x12\x1d\n" +
	"\n" +
	"exp_gained\x18\x01 \x01(\x05R\texpGained\x12\x1b\n" +
	"\tnew_level\x18\x02 \x01(\x05R\bnewLevel\x12)\n" +
	"\x10consecutive_days\x18\x03 \x01(\x05R\x0fconsecutiveDays\x12\x19\n" +
	"\blevel_up\x18\x04 \x01(\bR\alevelUp\x12%\n" +
	"\x0especial_reward\x18\x05 \x01(\tR\rspecialReward\x12H\n" +
	"\x10new_achievements\x18\x06 \x03(\v2\x1d.checkin.v1.AchievementUnlockR\x0fnewAchievements\".\n" +
	"\x13GetUserLevelRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"M\n" +
	"\x11GetUserLevelReply\x128\n" +
	"\n" +
	"level_info\x18\x01 \x01(\v2\x19.checkin.v1.UserLevelInfoR\tlevelInfo\"2\n" +
	"\x17GetCheckInStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"J\n" +
	"\x15GetCheckInStatusReply\x121\n" +
	"\x06status\x18\x01 \x01(\v2\x19.checkin.v1.CheckInStatusR\x06status\"d\n" +
	"\x18GetCheckInHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"c\n" +
	"\x16GetCheckInHistoryReply\x123\n" +
	"\arecords\x18\x01 \x03(\v2\x19.checkin.v1.CheckInRecordR\arecords\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"]\n" +
	"\x11GetExpLogsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"U\n" +
	"\x0fGetExpLogsReply\x12,\n" +
	"\x04logs\x18\x01 \x03(\v2\x18.checkin.v1.ExpLogRecordR\x04logs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\x9f\x03\n" +
	"\aCheckin\x12?\n" +
	"\aCheckIn\x12\x1a.checkin.v1.CheckInRequest\x1a\x18.checkin.v1.CheckInReply\x12N\n" +
	"\fGetUserLevel\x12\x1f.checkin.v1.GetUserLevelRequest\x1a\x1d.checkin.v1.GetUserLevelReply\x12Z\n" +
	"\x10GetCheckInStatus\x12#.checkin.v1.GetCheckInStatusRequest\x1a!.checkin.v1.GetCheckInStatusReply\x12]\n" +
	"\x11GetCheckInHistory\x12$.checkin.v1.GetCheckInHistoryRequest\x1a\".checkin.v1.GetCheckInHistoryReply\x12H\n" +
	"\n" +
	"GetExpLogs\x12\x1d.checkin.v1.GetExpLogsRequest\x1a\x1b.checkin.v1.GetExpLogsReplyB\"Z backend/api/checkin/v1;checkinv1b\x06proto3"

var (
	file_api_checkin_v1_checkin_proto_rawDescOnce sync.Once
	file_api_checkin_v1_checkin_proto_rawDescData []byte
)

func file_api_checkin_v1_checkin_proto_rawDescGZIP() []byte {
	file_api_checkin_v1_checkin_proto_rawDescOnce.Do(func() {
		file_api_checkin_v1_checkin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_checkin_v1_checkin_proto_rawDesc), len(file_api_checkin_v1_checkin_proto_rawDesc)))
	})
	return file_api_checkin_v1_checkin_proto_rawDescData
}

var file_api_checkin_v1_checkin_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_checkin_v1_checkin_proto_goTypes = []any{
	(*UserLevelInfo)(nil),            // 0: checkin.v1.UserLevelInfo
	(*CheckInStatus)(nil),            // 1: checkin.v1.CheckInStatus
	(*CheckInRecord)(nil),            // 2: checkin.v1.CheckInRecord
	(*ExpLogRecord)(nil),             // 3: checkin.v1.ExpLogRecord
	(*AchievementUnlock)(nil),        // 4: checkin.v1.AchievementUnlock
	(*CheckInRequest)(nil),           // 5: checkin.v1.CheckInRequest
	(*CheckInReply)(nil),             // 6: checkin.v1.CheckInReply
	(*GetUserLevelRequest)(nil),      // 7: checkin.v1.GetUserLevelRequest
	(*GetUserLevelReply)(nil),        // 8: checkin.v1.GetUserLevelReply
	(*GetCheckInStatusRequest)(nil),  // 9: checkin.v1.GetCheckInStatusRequest
	(*GetCheckInStatusReply)(nil),    // 10: checkin.v1.GetCheckInStatusReply
	(*GetCheckInHistoryRequest)(nil), // 11: checkin.v1.GetCheckInHistoryRequest
	(*GetCheckInHistoryReply)(nil),   // 12: checkin.v1.GetCheckInHistoryReply
	(*GetExpLogsRequest)(nil),        // 13: checkin.v1.GetExpLogsRequest
	(*GetExpLogsReply)(nil),          // 14: checkin.v1.GetExpLogsReply
}
var file_api_checkin_v1_checkin_proto_depIdxs = []int32{
	4,  // 0: checkin.v1.CheckInReply.new_achievements:type_name -> checkin.v1.AchievementUnlock
	0,  // 1: checkin.v1.GetUserLevelReply.level_info:type_name -> checkin.v1.UserLevelInfo
	1,  // 2: checkin.v1.GetCheckInStatusReply.status:type_name -> checkin.v1.CheckInStatus
	2,  // 3: checkin.v1.GetCheckInHistoryReply.records:type_name -> checkin.v1.CheckInRecord
	3,  // 4: checkin.v1.GetExpLogsReply.logs:type_name -> checkin.v1.ExpLogRecord
	5,  // 5: checkin.v1.Checkin.CheckIn:input_type -> checkin.v1.CheckInRequest
	7,  // 6: checkin.v1.Checkin.GetUserLevel:input_type -> checkin.v1.GetUserLevelRequest
	9,  // 7: checkin.v1.Checkin.GetCheckInStatus:input_type -> checkin.v1.GetCheckInStatusRequest
	11, // 8: checkin.v1.Checkin.GetCheckInHistory:input_type -> checkin.v1.GetCheckInHistoryRequest
	13, // 9: checkin.v1.Checkin.GetExpLogs:input_type -> checkin.v1.GetExpLogsRequest
	6,  // 10: checkin.v1.Checkin.CheckIn:output_type -> checkin.v1.CheckInReply
	8,  // 11: checkin.v1.Checkin.GetUserLevel:output_type -> checkin.v1.GetUserLevelReply
	10, // 12: checkin.v1.Checkin.GetCheckInStatus:output_type -> checkin.v1.GetCheckInStatusReply
	12, // 13: checkin.v1.Checkin.GetCheckInHistory:output_type -> checkin.v1.GetCheckInHistoryReply
	14, // 14: checkin.v1.Checkin.GetExpLogs:output_type -> checkin.v1.GetExpLogsReply
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_checkin_v1_checkin_proto_init() }
func file_api_checkin_v1_checkin_proto_init() {
	if File_api_checkin_v1_checkin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_checkin_v1_checkin_proto_rawDesc), len(file_api_checkin_v1_checkin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_checkin_v1_checkin_proto_goTypes,
		DependencyIndexes: file_api_checkin_v1_checkin_proto_depIdxs,
		MessageInfos:      file_api_checkin_v1_checkin_proto_msgTypes,
	}.Build()
	File_api_checkin_v1_checkin_proto = out.File
	file_api_checkin_v1_checkin_proto_goTypes = nil
	file_api_checkin_v1_checkin_proto_depIdxs = nil
}
