// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.1
// source: api/checkin/v1/checkin.proto

package checkinv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCheckinCheckIn = "/checkin.v1.Checkin/CheckIn"
const OperationCheckinClaimDailyExp = "/checkin.v1.Checkin/ClaimDailyExp"
const OperationCheckinGetCheckInHistory = "/checkin.v1.Checkin/GetCheckInHistory"
const OperationCheckinGetCheckInStatus = "/checkin.v1.Checkin/GetCheckInStatus"
const OperationCheckinGetExpLogs = "/checkin.v1.Checkin/GetExpLogs"
const OperationCheckinGetUserLevel = "/checkin.v1.Checkin/GetUserLevel"

type CheckinHTTPServer interface {
	CheckIn(context.Context, *CheckInRequest) (*CheckInReply, error)
	ClaimDailyExp(context.Context, *ClaimDailyExpRequest) (*ClaimDailyExpReply, error)
	GetCheckInHistory(context.Context, *GetCheckInHistoryRequest) (*GetCheckInHistoryReply, error)
	GetCheckInStatus(context.Context, *GetCheckInStatusRequest) (*GetCheckInStatusReply, error)
	GetExpLogs(context.Context, *GetExpLogsRequest) (*GetExpLogsReply, error)
	GetUserLevel(context.Context, *GetUserLevelRequest) (*GetUserLevelReply, error)
}

func RegisterCheckinHTTPServer(s *http.Server, srv CheckinHTTPServer) {
	r := s.Route("/")
	r.POST("/api/user/{user_id}/check-in", _Checkin_CheckIn0_HTTP_Handler(srv))
	r.GET("/api/user/{user_id}/level", _Checkin_GetUserLevel0_HTTP_Handler(srv))
	r.GET("/api/user/{user_id}/check-in/status", _Checkin_GetCheckInStatus0_HTTP_Handler(srv))
	r.GET("/api/user/{user_id}/check-in/history", _Checkin_GetCheckInHistory0_HTTP_Handler(srv))
	r.GET("/api/user/{user_id}/exp/logs", _Checkin_GetExpLogs0_HTTP_Handler(srv))
	r.POST("/api/user/{user_id}/daily-exp", _Checkin_ClaimDailyExp0_HTTP_Handler(srv))
}

func _Checkin_CheckIn0_HTTP_Handler(srv CheckinHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckInRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCheckinCheckIn)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CheckIn(ctx, req.(*CheckInRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckInReply)
		return ctx.Result(200, reply)
	}
}

func _Checkin_GetUserLevel0_HTTP_Handler(srv CheckinHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserLevelRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCheckinGetUserLevel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserLevel(ctx, req.(*GetUserLevelRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserLevelReply)
		return ctx.Result(200, reply)
	}
}

func _Checkin_GetCheckInStatus0_HTTP_Handler(srv CheckinHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCheckInStatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCheckinGetCheckInStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCheckInStatus(ctx, req.(*GetCheckInStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCheckInStatusReply)
		return ctx.Result(200, reply)
	}
}

func _Checkin_GetCheckInHistory0_HTTP_Handler(srv CheckinHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCheckInHistoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCheckinGetCheckInHistory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCheckInHistory(ctx, req.(*GetCheckInHistoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCheckInHistoryReply)
		return ctx.Result(200, reply)
	}
}

func _Checkin_GetExpLogs0_HTTP_Handler(srv CheckinHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetExpLogsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCheckinGetExpLogs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetExpLogs(ctx, req.(*GetExpLogsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetExpLogsReply)
		return ctx.Result(200, reply)
	}
}

func _Checkin_ClaimDailyExp0_HTTP_Handler(srv CheckinHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ClaimDailyExpRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCheckinClaimDailyExp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ClaimDailyExp(ctx, req.(*ClaimDailyExpRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ClaimDailyExpReply)
		return ctx.Result(200, reply)
	}
}

type CheckinHTTPClient interface {
	CheckIn(ctx context.Context, req *CheckInRequest, opts ...http.CallOption) (rsp *CheckInReply, err error)
	ClaimDailyExp(ctx context.Context, req *ClaimDailyExpRequest, opts ...http.CallOption) (rsp *ClaimDailyExpReply, err error)
	GetCheckInHistory(ctx context.Context, req *GetCheckInHistoryRequest, opts ...http.CallOption) (rsp *GetCheckInHistoryReply, err error)
	GetCheckInStatus(ctx context.Context, req *GetCheckInStatusRequest, opts ...http.CallOption) (rsp *GetCheckInStatusReply, err error)
	GetExpLogs(ctx context.Context, req *GetExpLogsRequest, opts ...http.CallOption) (rsp *GetExpLogsReply, err error)
	GetUserLevel(ctx context.Context, req *GetUserLevelRequest, opts ...http.CallOption) (rsp *GetUserLevelReply, err error)
}

type CheckinHTTPClientImpl struct {
	cc *http.Client
}

func NewCheckinHTTPClient(client *http.Client) CheckinHTTPClient {
	return &CheckinHTTPClientImpl{client}
}

func (c *CheckinHTTPClientImpl) CheckIn(ctx context.Context, in *CheckInRequest, opts ...http.CallOption) (*CheckInReply, error) {
	var out CheckInReply
	pattern := "/api/user/{user_id}/check-in"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCheckinCheckIn))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CheckinHTTPClientImpl) ClaimDailyExp(ctx context.Context, in *ClaimDailyExpRequest, opts ...http.CallOption) (*ClaimDailyExpReply, error) {
	var out ClaimDailyExpReply
	pattern := "/api/user/{user_id}/daily-exp"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCheckinClaimDailyExp))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CheckinHTTPClientImpl) GetCheckInHistory(ctx context.Context, in *GetCheckInHistoryRequest, opts ...http.CallOption) (*GetCheckInHistoryReply, error) {
	var out GetCheckInHistoryReply
	pattern := "/api/user/{user_id}/check-in/history"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCheckinGetCheckInHistory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CheckinHTTPClientImpl) GetCheckInStatus(ctx context.Context, in *GetCheckInStatusRequest, opts ...http.CallOption) (*GetCheckInStatusReply, error) {
	var out GetCheckInStatusReply
	pattern := "/api/user/{user_id}/check-in/status"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCheckinGetCheckInStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CheckinHTTPClientImpl) GetExpLogs(ctx context.Context, in *GetExpLogsRequest, opts ...http.CallOption) (*GetExpLogsReply, error) {
	var out GetExpLogsReply
	pattern := "/api/user/{user_id}/exp/logs"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCheckinGetExpLogs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CheckinHTTPClientImpl) GetUserLevel(ctx context.Context, in *GetUserLevelRequest, opts ...http.CallOption) (*GetUserLevelReply, error) {
	var out GetUserLevelReply
	pattern := "/api/user/{user_id}/level"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCheckinGetUserLevel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
