// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: api/platform/v1/platform_messages.proto

package platformv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Platform_GetPublicClientConfig_FullMethodName = "/platform.v1.Platform/GetPublicClientConfig"
	Platform_ListUserContent_FullMethodName       = "/platform.v1.Platform/ListUserContent"
	Platform_LlmChatRaw_FullMethodName            = "/platform.v1.Platform/LlmChatRaw"
	Platform_GetLlmConfig_FullMethodName          = "/platform.v1.Platform/GetLlmConfig"
	Platform_LlmModelsRaw_FullMethodName          = "/platform.v1.Platform/LlmModelsRaw"
	Platform_LlmShowRaw_FullMethodName            = "/platform.v1.Platform/LlmShowRaw"
	Platform_MoeExecuteTool_FullMethodName        = "/platform.v1.Platform/MoeExecuteTool"
	Platform_MoeToolsSchema_FullMethodName        = "/platform.v1.Platform/MoeToolsSchema"
	Platform_VoiceAnswer_FullMethodName           = "/platform.v1.Platform/VoiceAnswer"
	Platform_VoiceCall_FullMethodName             = "/platform.v1.Platform/VoiceCall"
	Platform_VoiceCancel_FullMethodName           = "/platform.v1.Platform/VoiceCancel"
	Platform_VoiceReject_FullMethodName           = "/platform.v1.Platform/VoiceReject"
	Platform_GetVoiceToken_FullMethodName         = "/platform.v1.Platform/GetVoiceToken"
	Platform_LlmCreateAgent_FullMethodName        = "/platform.v1.Platform/LlmCreateAgent"
	Platform_LlmChat_FullMethodName               = "/platform.v1.Platform/LlmChat"
	Platform_LlmDeleteModel_FullMethodName        = "/platform.v1.Platform/LlmDeleteModel"
	Platform_LlmDownloadModel_FullMethodName      = "/platform.v1.Platform/LlmDownloadModel"
	Platform_ListAnnouncements_FullMethodName     = "/platform.v1.Platform/ListAnnouncements"
	Platform_GetAnnouncement_FullMethodName       = "/platform.v1.Platform/GetAnnouncement"
)

// PlatformClient is the client API for Platform service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlatformClient interface {
	GetPublicClientConfig(ctx context.Context, in *GetPublicClientConfigReq, opts ...grpc.CallOption) (*GetPublicClientConfigResp, error)
	ListUserContent(ctx context.Context, in *ListUserContentReq, opts ...grpc.CallOption) (*ListUserContentResp, error)
	LlmChatRaw(ctx context.Context, in *LlmRawProxyReq, opts ...grpc.CallOption) (*LlmRawProxyResp, error)
	GetLlmConfig(ctx context.Context, in *GetLlmConfigReq, opts ...grpc.CallOption) (*GetLlmConfigResp, error)
	LlmModelsRaw(ctx context.Context, in *LlmRawProxyReq, opts ...grpc.CallOption) (*LlmRawProxyResp, error)
	LlmShowRaw(ctx context.Context, in *LlmRawProxyReq, opts ...grpc.CallOption) (*LlmRawProxyResp, error)
	MoeExecuteTool(ctx context.Context, in *MoeToolExecuteReq, opts ...grpc.CallOption) (*MoeToolExecuteResp, error)
	MoeToolsSchema(ctx context.Context, in *MoeToolSchemaReq, opts ...grpc.CallOption) (*MoeToolSchemaResp, error)
	VoiceAnswer(ctx context.Context, in *VoiceAnswerReq, opts ...grpc.CallOption) (*VoiceAnswerResp, error)
	VoiceCall(ctx context.Context, in *VoiceCallReq, opts ...grpc.CallOption) (*VoiceCallResp, error)
	VoiceCancel(ctx context.Context, in *VoiceCancelReq, opts ...grpc.CallOption) (*VoiceSimpleResp, error)
	VoiceReject(ctx context.Context, in *VoiceRejectReq, opts ...grpc.CallOption) (*VoiceSimpleResp, error)
	GetVoiceToken(ctx context.Context, in *GetVoiceTokenReq, opts ...grpc.CallOption) (*GetVoiceTokenResp, error)
	LlmCreateAgent(ctx context.Context, in *LlmCreateAgentReq, opts ...grpc.CallOption) (*BaseResp, error)
	LlmChat(ctx context.Context, in *LlmChatReq, opts ...grpc.CallOption) (*LlmChatResp, error)
	LlmDeleteModel(ctx context.Context, in *LlmDeleteModelReq, opts ...grpc.CallOption) (*BaseResp, error)
	LlmDownloadModel(ctx context.Context, in *LlmDownloadModelReq, opts ...grpc.CallOption) (*BaseResp, error)
	ListAnnouncements(ctx context.Context, in *ListAnnouncementsReq, opts ...grpc.CallOption) (*ListAnnouncementsResp, error)
	GetAnnouncement(ctx context.Context, in *GetAnnouncementReq, opts ...grpc.CallOption) (*GetAnnouncementResp, error)
}

type platformClient struct {
	cc grpc.ClientConnInterface
}

func NewPlatformClient(cc grpc.ClientConnInterface) PlatformClient {
	return &platformClient{cc}
}

func (c *platformClient) GetPublicClientConfig(ctx context.Context, in *GetPublicClientConfigReq, opts ...grpc.CallOption) (*GetPublicClientConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublicClientConfigResp)
	err := c.cc.Invoke(ctx, Platform_GetPublicClientConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) ListUserContent(ctx context.Context, in *ListUserContentReq, opts ...grpc.CallOption) (*ListUserContentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserContentResp)
	err := c.cc.Invoke(ctx, Platform_ListUserContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) LlmChatRaw(ctx context.Context, in *LlmRawProxyReq, opts ...grpc.CallOption) (*LlmRawProxyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LlmRawProxyResp)
	err := c.cc.Invoke(ctx, Platform_LlmChatRaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) GetLlmConfig(ctx context.Context, in *GetLlmConfigReq, opts ...grpc.CallOption) (*GetLlmConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLlmConfigResp)
	err := c.cc.Invoke(ctx, Platform_GetLlmConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) LlmModelsRaw(ctx context.Context, in *LlmRawProxyReq, opts ...grpc.CallOption) (*LlmRawProxyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LlmRawProxyResp)
	err := c.cc.Invoke(ctx, Platform_LlmModelsRaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) LlmShowRaw(ctx context.Context, in *LlmRawProxyReq, opts ...grpc.CallOption) (*LlmRawProxyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LlmRawProxyResp)
	err := c.cc.Invoke(ctx, Platform_LlmShowRaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) MoeExecuteTool(ctx context.Context, in *MoeToolExecuteReq, opts ...grpc.CallOption) (*MoeToolExecuteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoeToolExecuteResp)
	err := c.cc.Invoke(ctx, Platform_MoeExecuteTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) MoeToolsSchema(ctx context.Context, in *MoeToolSchemaReq, opts ...grpc.CallOption) (*MoeToolSchemaResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoeToolSchemaResp)
	err := c.cc.Invoke(ctx, Platform_MoeToolsSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) VoiceAnswer(ctx context.Context, in *VoiceAnswerReq, opts ...grpc.CallOption) (*VoiceAnswerResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoiceAnswerResp)
	err := c.cc.Invoke(ctx, Platform_VoiceAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) VoiceCall(ctx context.Context, in *VoiceCallReq, opts ...grpc.CallOption) (*VoiceCallResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoiceCallResp)
	err := c.cc.Invoke(ctx, Platform_VoiceCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) VoiceCancel(ctx context.Context, in *VoiceCancelReq, opts ...grpc.CallOption) (*VoiceSimpleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoiceSimpleResp)
	err := c.cc.Invoke(ctx, Platform_VoiceCancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) VoiceReject(ctx context.Context, in *VoiceRejectReq, opts ...grpc.CallOption) (*VoiceSimpleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoiceSimpleResp)
	err := c.cc.Invoke(ctx, Platform_VoiceReject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) GetVoiceToken(ctx context.Context, in *GetVoiceTokenReq, opts ...grpc.CallOption) (*GetVoiceTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVoiceTokenResp)
	err := c.cc.Invoke(ctx, Platform_GetVoiceToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) LlmCreateAgent(ctx context.Context, in *LlmCreateAgentReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Platform_LlmCreateAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) LlmChat(ctx context.Context, in *LlmChatReq, opts ...grpc.CallOption) (*LlmChatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LlmChatResp)
	err := c.cc.Invoke(ctx, Platform_LlmChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) LlmDeleteModel(ctx context.Context, in *LlmDeleteModelReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Platform_LlmDeleteModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) LlmDownloadModel(ctx context.Context, in *LlmDownloadModelReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Platform_LlmDownloadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) ListAnnouncements(ctx context.Context, in *ListAnnouncementsReq, opts ...grpc.CallOption) (*ListAnnouncementsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAnnouncementsResp)
	err := c.cc.Invoke(ctx, Platform_ListAnnouncements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) GetAnnouncement(ctx context.Context, in *GetAnnouncementReq, opts ...grpc.CallOption) (*GetAnnouncementResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnnouncementResp)
	err := c.cc.Invoke(ctx, Platform_GetAnnouncement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformServer is the server API for Platform service.
// All implementations must embed UnimplementedPlatformServer
// for forward compatibility.
type PlatformServer interface {
	GetPublicClientConfig(context.Context, *GetPublicClientConfigReq) (*GetPublicClientConfigResp, error)
	ListUserContent(context.Context, *ListUserContentReq) (*ListUserContentResp, error)
	LlmChatRaw(context.Context, *LlmRawProxyReq) (*LlmRawProxyResp, error)
	GetLlmConfig(context.Context, *GetLlmConfigReq) (*GetLlmConfigResp, error)
	LlmModelsRaw(context.Context, *LlmRawProxyReq) (*LlmRawProxyResp, error)
	LlmShowRaw(context.Context, *LlmRawProxyReq) (*LlmRawProxyResp, error)
	MoeExecuteTool(context.Context, *MoeToolExecuteReq) (*MoeToolExecuteResp, error)
	MoeToolsSchema(context.Context, *MoeToolSchemaReq) (*MoeToolSchemaResp, error)
	VoiceAnswer(context.Context, *VoiceAnswerReq) (*VoiceAnswerResp, error)
	VoiceCall(context.Context, *VoiceCallReq) (*VoiceCallResp, error)
	VoiceCancel(context.Context, *VoiceCancelReq) (*VoiceSimpleResp, error)
	VoiceReject(context.Context, *VoiceRejectReq) (*VoiceSimpleResp, error)
	GetVoiceToken(context.Context, *GetVoiceTokenReq) (*GetVoiceTokenResp, error)
	LlmCreateAgent(context.Context, *LlmCreateAgentReq) (*BaseResp, error)
	LlmChat(context.Context, *LlmChatReq) (*LlmChatResp, error)
	LlmDeleteModel(context.Context, *LlmDeleteModelReq) (*BaseResp, error)
	LlmDownloadModel(context.Context, *LlmDownloadModelReq) (*BaseResp, error)
	ListAnnouncements(context.Context, *ListAnnouncementsReq) (*ListAnnouncementsResp, error)
	GetAnnouncement(context.Context, *GetAnnouncementReq) (*GetAnnouncementResp, error)
	mustEmbedUnimplementedPlatformServer()
}

// UnimplementedPlatformServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlatformServer struct{}

func (UnimplementedPlatformServer) GetPublicClientConfig(context.Context, *GetPublicClientConfigReq) (*GetPublicClientConfigResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublicClientConfig not implemented")
}
func (UnimplementedPlatformServer) ListUserContent(context.Context, *ListUserContentReq) (*ListUserContentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserContent not implemented")
}
func (UnimplementedPlatformServer) LlmChatRaw(context.Context, *LlmRawProxyReq) (*LlmRawProxyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LlmChatRaw not implemented")
}
func (UnimplementedPlatformServer) GetLlmConfig(context.Context, *GetLlmConfigReq) (*GetLlmConfigResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLlmConfig not implemented")
}
func (UnimplementedPlatformServer) LlmModelsRaw(context.Context, *LlmRawProxyReq) (*LlmRawProxyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LlmModelsRaw not implemented")
}
func (UnimplementedPlatformServer) LlmShowRaw(context.Context, *LlmRawProxyReq) (*LlmRawProxyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LlmShowRaw not implemented")
}
func (UnimplementedPlatformServer) MoeExecuteTool(context.Context, *MoeToolExecuteReq) (*MoeToolExecuteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MoeExecuteTool not implemented")
}
func (UnimplementedPlatformServer) MoeToolsSchema(context.Context, *MoeToolSchemaReq) (*MoeToolSchemaResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MoeToolsSchema not implemented")
}
func (UnimplementedPlatformServer) VoiceAnswer(context.Context, *VoiceAnswerReq) (*VoiceAnswerResp, error) {
	return nil, status.Error(codes.Unimplemented, "method VoiceAnswer not implemented")
}
func (UnimplementedPlatformServer) VoiceCall(context.Context, *VoiceCallReq) (*VoiceCallResp, error) {
	return nil, status.Error(codes.Unimplemented, "method VoiceCall not implemented")
}
func (UnimplementedPlatformServer) VoiceCancel(context.Context, *VoiceCancelReq) (*VoiceSimpleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method VoiceCancel not implemented")
}
func (UnimplementedPlatformServer) VoiceReject(context.Context, *VoiceRejectReq) (*VoiceSimpleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method VoiceReject not implemented")
}
func (UnimplementedPlatformServer) GetVoiceToken(context.Context, *GetVoiceTokenReq) (*GetVoiceTokenResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVoiceToken not implemented")
}
func (UnimplementedPlatformServer) LlmCreateAgent(context.Context, *LlmCreateAgentReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LlmCreateAgent not implemented")
}
func (UnimplementedPlatformServer) LlmChat(context.Context, *LlmChatReq) (*LlmChatResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LlmChat not implemented")
}
func (UnimplementedPlatformServer) LlmDeleteModel(context.Context, *LlmDeleteModelReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LlmDeleteModel not implemented")
}
func (UnimplementedPlatformServer) LlmDownloadModel(context.Context, *LlmDownloadModelReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LlmDownloadModel not implemented")
}
func (UnimplementedPlatformServer) ListAnnouncements(context.Context, *ListAnnouncementsReq) (*ListAnnouncementsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAnnouncements not implemented")
}
func (UnimplementedPlatformServer) GetAnnouncement(context.Context, *GetAnnouncementReq) (*GetAnnouncementResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnnouncement not implemented")
}
func (UnimplementedPlatformServer) mustEmbedUnimplementedPlatformServer() {}
func (UnimplementedPlatformServer) testEmbeddedByValue()                  {}

// UnsafePlatformServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlatformServer will
// result in compilation errors.
type UnsafePlatformServer interface {
	mustEmbedUnimplementedPlatformServer()
}

func RegisterPlatformServer(s grpc.ServiceRegistrar, srv PlatformServer) {
	// If the following call panics, it indicates UnimplementedPlatformServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Platform_ServiceDesc, srv)
}

func _Platform_GetPublicClientConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicClientConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).GetPublicClientConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_GetPublicClientConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).GetPublicClientConfig(ctx, req.(*GetPublicClientConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_ListUserContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserContentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).ListUserContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_ListUserContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).ListUserContent(ctx, req.(*ListUserContentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_LlmChatRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LlmRawProxyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).LlmChatRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_LlmChatRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).LlmChatRaw(ctx, req.(*LlmRawProxyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_GetLlmConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLlmConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).GetLlmConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_GetLlmConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).GetLlmConfig(ctx, req.(*GetLlmConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_LlmModelsRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LlmRawProxyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).LlmModelsRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_LlmModelsRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).LlmModelsRaw(ctx, req.(*LlmRawProxyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_LlmShowRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LlmRawProxyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).LlmShowRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_LlmShowRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).LlmShowRaw(ctx, req.(*LlmRawProxyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_MoeExecuteTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoeToolExecuteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).MoeExecuteTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_MoeExecuteTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).MoeExecuteTool(ctx, req.(*MoeToolExecuteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_MoeToolsSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoeToolSchemaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).MoeToolsSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_MoeToolsSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).MoeToolsSchema(ctx, req.(*MoeToolSchemaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_VoiceAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoiceAnswerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).VoiceAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_VoiceAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).VoiceAnswer(ctx, req.(*VoiceAnswerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_VoiceCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoiceCallReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).VoiceCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_VoiceCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).VoiceCall(ctx, req.(*VoiceCallReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_VoiceCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoiceCancelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).VoiceCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_VoiceCancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).VoiceCancel(ctx, req.(*VoiceCancelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_VoiceReject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoiceRejectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).VoiceReject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_VoiceReject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).VoiceReject(ctx, req.(*VoiceRejectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_GetVoiceToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVoiceTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).GetVoiceToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_GetVoiceToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).GetVoiceToken(ctx, req.(*GetVoiceTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_LlmCreateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LlmCreateAgentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).LlmCreateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_LlmCreateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).LlmCreateAgent(ctx, req.(*LlmCreateAgentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_LlmChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LlmChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).LlmChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_LlmChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).LlmChat(ctx, req.(*LlmChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_LlmDeleteModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LlmDeleteModelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).LlmDeleteModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_LlmDeleteModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).LlmDeleteModel(ctx, req.(*LlmDeleteModelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_LlmDownloadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LlmDownloadModelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).LlmDownloadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_LlmDownloadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).LlmDownloadModel(ctx, req.(*LlmDownloadModelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_ListAnnouncements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAnnouncementsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).ListAnnouncements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_ListAnnouncements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).ListAnnouncements(ctx, req.(*ListAnnouncementsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_GetAnnouncement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnnouncementReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).GetAnnouncement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Platform_GetAnnouncement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).GetAnnouncement(ctx, req.(*GetAnnouncementReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Platform_ServiceDesc is the grpc.ServiceDesc for Platform service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Platform_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform.v1.Platform",
	HandlerType: (*PlatformServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublicClientConfig",
			Handler:    _Platform_GetPublicClientConfig_Handler,
		},
		{
			MethodName: "ListUserContent",
			Handler:    _Platform_ListUserContent_Handler,
		},
		{
			MethodName: "LlmChatRaw",
			Handler:    _Platform_LlmChatRaw_Handler,
		},
		{
			MethodName: "GetLlmConfig",
			Handler:    _Platform_GetLlmConfig_Handler,
		},
		{
			MethodName: "LlmModelsRaw",
			Handler:    _Platform_LlmModelsRaw_Handler,
		},
		{
			MethodName: "LlmShowRaw",
			Handler:    _Platform_LlmShowRaw_Handler,
		},
		{
			MethodName: "MoeExecuteTool",
			Handler:    _Platform_MoeExecuteTool_Handler,
		},
		{
			MethodName: "MoeToolsSchema",
			Handler:    _Platform_MoeToolsSchema_Handler,
		},
		{
			MethodName: "VoiceAnswer",
			Handler:    _Platform_VoiceAnswer_Handler,
		},
		{
			MethodName: "VoiceCall",
			Handler:    _Platform_VoiceCall_Handler,
		},
		{
			MethodName: "VoiceCancel",
			Handler:    _Platform_VoiceCancel_Handler,
		},
		{
			MethodName: "VoiceReject",
			Handler:    _Platform_VoiceReject_Handler,
		},
		{
			MethodName: "GetVoiceToken",
			Handler:    _Platform_GetVoiceToken_Handler,
		},
		{
			MethodName: "LlmCreateAgent",
			Handler:    _Platform_LlmCreateAgent_Handler,
		},
		{
			MethodName: "LlmChat",
			Handler:    _Platform_LlmChat_Handler,
		},
		{
			MethodName: "LlmDeleteModel",
			Handler:    _Platform_LlmDeleteModel_Handler,
		},
		{
			MethodName: "LlmDownloadModel",
			Handler:    _Platform_LlmDownloadModel_Handler,
		},
		{
			MethodName: "ListAnnouncements",
			Handler:    _Platform_ListAnnouncements_Handler,
		},
		{
			MethodName: "GetAnnouncement",
			Handler:    _Platform_GetAnnouncement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/platform/v1/platform_messages.proto",
}
