// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/arena/v1/arena.proto

package arenav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Arena_GetState_FullMethodName     = "/arena.v1.Arena/GetState"
	Arena_SetFormation_FullMethodName = "/arena.v1.Arena/SetFormation"
	Arena_SaveDeck_FullMethodName     = "/arena.v1.Arena/SaveDeck"
	Arena_Summon_FullMethodName       = "/arena.v1.Arena/Summon"
	Arena_HomeGift_FullMethodName     = "/arena.v1.Arena/HomeGift"
	Arena_ClearTower_FullMethodName   = "/arena.v1.Arena/ClearTower"
)

// ArenaClient is the client API for Arena service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArenaClient interface {
	GetState(ctx context.Context, in *GetArenaStateRequest, opts ...grpc.CallOption) (*GetArenaStateReply, error)
	SetFormation(ctx context.Context, in *SetFormationRequest, opts ...grpc.CallOption) (*SetFormationReply, error)
	SaveDeck(ctx context.Context, in *SaveDeckRequest, opts ...grpc.CallOption) (*SaveDeckReply, error)
	Summon(ctx context.Context, in *SummonRequest, opts ...grpc.CallOption) (*SummonReply, error)
	HomeGift(ctx context.Context, in *HomeGiftRequest, opts ...grpc.CallOption) (*HomeGiftReply, error)
	ClearTower(ctx context.Context, in *ClearTowerRequest, opts ...grpc.CallOption) (*ClearTowerReply, error)
}

type arenaClient struct {
	cc grpc.ClientConnInterface
}

func NewArenaClient(cc grpc.ClientConnInterface) ArenaClient {
	return &arenaClient{cc}
}

func (c *arenaClient) GetState(ctx context.Context, in *GetArenaStateRequest, opts ...grpc.CallOption) (*GetArenaStateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArenaStateReply)
	err := c.cc.Invoke(ctx, Arena_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaClient) SetFormation(ctx context.Context, in *SetFormationRequest, opts ...grpc.CallOption) (*SetFormationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetFormationReply)
	err := c.cc.Invoke(ctx, Arena_SetFormation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaClient) SaveDeck(ctx context.Context, in *SaveDeckRequest, opts ...grpc.CallOption) (*SaveDeckReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveDeckReply)
	err := c.cc.Invoke(ctx, Arena_SaveDeck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaClient) Summon(ctx context.Context, in *SummonRequest, opts ...grpc.CallOption) (*SummonReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummonReply)
	err := c.cc.Invoke(ctx, Arena_Summon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaClient) HomeGift(ctx context.Context, in *HomeGiftRequest, opts ...grpc.CallOption) (*HomeGiftReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HomeGiftReply)
	err := c.cc.Invoke(ctx, Arena_HomeGift_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaClient) ClearTower(ctx context.Context, in *ClearTowerRequest, opts ...grpc.CallOption) (*ClearTowerReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearTowerReply)
	err := c.cc.Invoke(ctx, Arena_ClearTower_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArenaServer is the server API for Arena service.
// All implementations must embed UnimplementedArenaServer
// for forward compatibility.
type ArenaServer interface {
	GetState(context.Context, *GetArenaStateRequest) (*GetArenaStateReply, error)
	SetFormation(context.Context, *SetFormationRequest) (*SetFormationReply, error)
	SaveDeck(context.Context, *SaveDeckRequest) (*SaveDeckReply, error)
	Summon(context.Context, *SummonRequest) (*SummonReply, error)
	HomeGift(context.Context, *HomeGiftRequest) (*HomeGiftReply, error)
	ClearTower(context.Context, *ClearTowerRequest) (*ClearTowerReply, error)
	mustEmbedUnimplementedArenaServer()
}

// UnimplementedArenaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArenaServer struct{}

func (UnimplementedArenaServer) GetState(context.Context, *GetArenaStateRequest) (*GetArenaStateReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedArenaServer) SetFormation(context.Context, *SetFormationRequest) (*SetFormationReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SetFormation not implemented")
}
func (UnimplementedArenaServer) SaveDeck(context.Context, *SaveDeckRequest) (*SaveDeckReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveDeck not implemented")
}
func (UnimplementedArenaServer) Summon(context.Context, *SummonRequest) (*SummonReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Summon not implemented")
}
func (UnimplementedArenaServer) HomeGift(context.Context, *HomeGiftRequest) (*HomeGiftReply, error) {
	return nil, status.Error(codes.Unimplemented, "method HomeGift not implemented")
}
func (UnimplementedArenaServer) ClearTower(context.Context, *ClearTowerRequest) (*ClearTowerReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearTower not implemented")
}
func (UnimplementedArenaServer) mustEmbedUnimplementedArenaServer() {}
func (UnimplementedArenaServer) testEmbeddedByValue()               {}

// UnsafeArenaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArenaServer will
// result in compilation errors.
type UnsafeArenaServer interface {
	mustEmbedUnimplementedArenaServer()
}

func RegisterArenaServer(s grpc.ServiceRegistrar, srv ArenaServer) {
	// If the following call panics, it indicates UnimplementedArenaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Arena_ServiceDesc, srv)
}

func _Arena_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArenaStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Arena_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServer).GetState(ctx, req.(*GetArenaStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Arena_SetFormation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFormationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServer).SetFormation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Arena_SetFormation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServer).SetFormation(ctx, req.(*SetFormationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Arena_SaveDeck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveDeckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServer).SaveDeck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Arena_SaveDeck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServer).SaveDeck(ctx, req.(*SaveDeckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Arena_Summon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServer).Summon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Arena_Summon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServer).Summon(ctx, req.(*SummonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Arena_HomeGift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeGiftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServer).HomeGift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Arena_HomeGift_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServer).HomeGift(ctx, req.(*HomeGiftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Arena_ClearTower_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearTowerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServer).ClearTower(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Arena_ClearTower_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServer).ClearTower(ctx, req.(*ClearTowerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Arena_ServiceDesc is the grpc.ServiceDesc for Arena service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Arena_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arena.v1.Arena",
	HandlerType: (*ArenaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _Arena_GetState_Handler,
		},
		{
			MethodName: "SetFormation",
			Handler:    _Arena_SetFormation_Handler,
		},
		{
			MethodName: "SaveDeck",
			Handler:    _Arena_SaveDeck_Handler,
		},
		{
			MethodName: "Summon",
			Handler:    _Arena_Summon_Handler,
		},
		{
			MethodName: "HomeGift",
			Handler:    _Arena_HomeGift_Handler,
		},
		{
			MethodName: "ClearTower",
			Handler:    _Arena_ClearTower_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/arena/v1/arena.proto",
}
