// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/achievement/v1/achievement.proto

package achievementv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AchievementApp_Ping_FullMethodName = "/achievement.v1.AchievementApp/Ping"
)

// AchievementAppClient is the client API for AchievementApp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AchievementAppClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
}

type achievementAppClient struct {
	cc grpc.ClientConnInterface
}

func NewAchievementAppClient(cc grpc.ClientConnInterface) AchievementAppClient {
	return &achievementAppClient{cc}
}

func (c *achievementAppClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingReply)
	err := c.cc.Invoke(ctx, AchievementApp_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AchievementAppServer is the server API for AchievementApp service.
// All implementations must embed UnimplementedAchievementAppServer
// for forward compatibility.
type AchievementAppServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	mustEmbedUnimplementedAchievementAppServer()
}

// UnimplementedAchievementAppServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAchievementAppServer struct{}

func (UnimplementedAchievementAppServer) Ping(context.Context, *PingRequest) (*PingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAchievementAppServer) mustEmbedUnimplementedAchievementAppServer() {}
func (UnimplementedAchievementAppServer) testEmbeddedByValue()                        {}

// UnsafeAchievementAppServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AchievementAppServer will
// result in compilation errors.
type UnsafeAchievementAppServer interface {
	mustEmbedUnimplementedAchievementAppServer()
}

func RegisterAchievementAppServer(s grpc.ServiceRegistrar, srv AchievementAppServer) {
	// If the following call panics, it indicates UnimplementedAchievementAppServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AchievementApp_ServiceDesc, srv)
}

func _AchievementApp_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AchievementAppServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AchievementApp_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AchievementAppServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AchievementApp_ServiceDesc is the grpc.ServiceDesc for AchievementApp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AchievementApp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "achievement.v1.AchievementApp",
	HandlerType: (*AchievementAppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _AchievementApp_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/achievement/v1/achievement.proto",
}
